-- L2 Stage: typed and cleaned staging Dynamic Tables
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- dbt staging views live in dbt_project/models/staging.
USE DATABASE ZERO_TO_ONE_CHAIN;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_INVENTORY(
	SNAPSHOT_DATE,
	PLANT_CODE,
	MATERIAL_NUMBER,
	STORAGE_LOCATION,
	STORAGE_TYPE,
	ON_HAND_QTY,
	ALLOCATED_QTY,
	AVAILABLE_QTY,
	IN_TRANSIT_QTY,
	ON_ORDER_QTY,
	QUARANTINE_QTY,
	UNIT_COST_USD,
	INVENTORY_VALUE_USD,
	REORDER_POINT,
	SAFETY_STOCK_QTY,
	STOCK_STATUS,
	DAYS_ON_HAND,
	ABC_CLASS,
	TURNOVER_RATIO,
	OBSOLESCENCE_RISK_PCT,
	VALUATION_METHOD,
	LAST_RECEIPT_DATE,
	LAST_ISSUE_DATE,
	COUNT_ACCURACY_PCT,
	LAST_CYCLE_COUNT_DATE,
	CARRYING_COST_USD_DAILY,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    snapshot_date::DATE AS snapshot_date,
    UPPER(TRIM(plant_code)) AS plant_code,
    UPPER(TRIM(material_number)) AS material_number,
    UPPER(TRIM(storage_location)) AS storage_location,
    UPPER(TRIM(storage_type)) AS storage_type,
    GREATEST(on_hand_qty, 0) AS on_hand_qty,
    GREATEST(allocated_qty, 0) AS allocated_qty,
    GREATEST(on_hand_qty - allocated_qty, 0) AS available_qty,
    GREATEST(in_transit_qty, 0) AS in_transit_qty,
    GREATEST(on_order_qty, 0) AS on_order_qty,
    GREATEST(quarantine_qty, 0) AS quarantine_qty,
    unit_cost_usd,
    ROUND(GREATEST(on_hand_qty, 0) * unit_cost_usd, 2) AS inventory_value_usd,
    reorder_point,
    safety_stock_qty,
    CASE
        WHEN on_hand_qty <= 0 THEN 'STOCKOUT'
        WHEN on_hand_qty <= reorder_point THEN 'BELOW_ROP'
        WHEN on_hand_qty <= safety_stock_qty THEN 'BELOW_SAFETY'
        ELSE 'ADEQUATE'
    END AS stock_status,
    days_on_hand,
    UPPER(TRIM(abc_classification)) AS abc_class,
    turnover_ratio,
    obsolescence_risk_pct,
    UPPER(TRIM(valuation_method)) AS valuation_method,
    last_receipt_date::DATE AS last_receipt_date,
    last_issue_date::DATE AS last_issue_date,
    count_accuracy_pct,
    last_cycle_count_date::DATE AS last_cycle_count_date,
    carrying_cost_usd_daily,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_IOT_READINGS(
	READING_ID,
	SENSOR_ID,
	SENSOR_TYPE,
	PLANT_CODE,
	LOCATION_ZONE,
	EQUIPMENT_ID,
	READING_TIMESTAMP,
	READING_VALUE,
	UNIT,
	LOWER_THRESHOLD,
	UPPER_THRESHOLD,
	ALERT_STATUS,
	BATTERY_LEVEL_PCT,
	SIGNAL_STRENGTH_DBM,
	CONNECTIVITY,
	DEVICE_STATUS,
	DAYS_SINCE_CALIBRATION,
	CALIBRATION_STATUS,
	DATA_QUALITY_SCORE,
	FIRMWARE_VERSION,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    reading_id,
    UPPER(TRIM(sensor_id)) AS sensor_id,
    UPPER(TRIM(sensor_type)) AS sensor_type,
    UPPER(TRIM(plant_code)) AS plant_code,
    UPPER(TRIM(location_zone)) AS location_zone,
    UPPER(TRIM(equipment_id)) AS equipment_id,
    reading_timestamp,
    reading_value,
    UPPER(TRIM(unit)) AS unit,
    lower_threshold,
    upper_threshold,
    CASE
        WHEN reading_value < lower_threshold OR reading_value > upper_threshold THEN 'ALARM'
        WHEN ABS(reading_value - (lower_threshold + upper_threshold) / 2) > (upper_threshold - lower_threshold) * 0.4 THEN 'WARNING'
        ELSE 'NORMAL'
    END AS alert_status,
    battery_level_pct,
    signal_strength_dbm,
    UPPER(TRIM(connectivity)) AS connectivity,
    UPPER(TRIM(device_status)) AS device_status,
    days_since_calibration,
    CASE
        WHEN days_since_calibration > 180 THEN 'OVERDUE'
        WHEN days_since_calibration > 90 THEN 'DUE_SOON'
        ELSE 'CURRENT'
    END AS calibration_status,
    data_quality_score,
    firmware_version,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_IOT_SENSOR_READINGS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_PURCHASE_ORDERS(
	PO_NUMBER,
	PO_HEADER_ID,
	LINE_NUMBER,
	PO_DATE,
	PO_TYPE,
	PO_STATUS,
	VENDOR_CODE,
	PLANT_CODE,
	MATERIAL_NUMBER,
	MATERIAL_GROUP,
	ORDERED_QTY,
	RECEIVED_QTY,
	REJECTED_QTY,
	UOM,
	UNIT_PRICE_LOCAL,
	PRICE_CURRENCY,
	FX_RATE_TO_USD,
	UNIT_PRICE_USD,
	EXTENDED_PRICE_USD,
	DISCOUNT_PCT,
	FREIGHT_COST_USD,
	DUTY_COST_USD,
	HANDLING_COST_USD,
	LANDED_COST_USD,
	REQUESTED_DELIVERY_DATE,
	CONFIRMED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	DELIVERY_VARIANCE_DAYS,
	IS_ON_TIME,
	IS_IN_FULL,
	IS_OTIF,
	PRIORITY,
	ORDER_SOURCE,
	BUYER_EMAIL,
	COST_CENTER,
	PROJECT_CODE,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    -- Keys
    po_number,
    po_header_id,
    line_number,
    -- Typed & normalized
    po_date::DATE AS po_date,
    UPPER(TRIM(po_type)) AS po_type,
    UPPER(TRIM(po_status)) AS po_status,
    UPPER(TRIM(vendor_code)) AS vendor_code,
    UPPER(TRIM(receiving_plant)) AS plant_code,
    UPPER(TRIM(material_number)) AS material_number,
    UPPER(TRIM(material_group)) AS material_group,
    -- Quantities (standardized to positive)
    GREATEST(ordered_qty, 0) AS ordered_qty,
    GREATEST(received_qty, 0) AS received_qty,
    GREATEST(rejected_qty, 0) AS rejected_qty,
    UPPER(TRIM(uom)) AS uom,
    -- Financials (normalized to USD)
    unit_price AS unit_price_local,
    UPPER(TRIM(price_currency)) AS price_currency,
    fx_rate_to_usd,
    ROUND(unit_price / NULLIF(fx_rate_to_usd, 0), 4) AS unit_price_usd,
    ROUND(ordered_qty * unit_price / NULLIF(fx_rate_to_usd, 0), 2) AS extended_price_usd,
    discount_pct,
    freight_cost_usd,
    duty_cost_usd,
    handling_cost_usd,
    ROUND(ordered_qty * unit_price / NULLIF(fx_rate_to_usd, 0) + COALESCE(freight_cost_usd, 0) + COALESCE(duty_cost_usd, 0) + COALESCE(handling_cost_usd, 0), 2) AS landed_cost_usd,
    -- Dates
    requested_delivery_date::DATE AS requested_delivery_date,
    confirmed_delivery_date::DATE AS confirmed_delivery_date,
    actual_delivery_date::DATE AS actual_delivery_date,
    -- Computed OTD (standardized definition)
    DATEDIFF(DAY, confirmed_delivery_date, actual_delivery_date) AS delivery_variance_days,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= confirmed_delivery_date THEN TRUE ELSE FALSE END AS is_on_time,
    CASE WHEN actual_delivery_date IS NOT NULL AND received_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_in_full,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= confirmed_delivery_date AND received_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_otif,
    -- Metadata
    UPPER(TRIM(priority)) AS priority,
    UPPER(TRIM(order_source)) AS order_source,
    buyer_email,
    cost_center,
    project_code,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_SALES_ORDERS(
	ORDER_NUMBER,
	ORDER_HEADER_ID,
	LINE_ITEM,
	ORDER_DATE,
	ORDER_TYPE,
	ORDER_STATUS,
	CUSTOMER_ID,
	PLANT_CODE,
	MATERIAL_NUMBER,
	ORDERED_QTY,
	SHIPPED_QTY,
	DELIVERED_QTY,
	UOM,
	UNIT_PRICE_USD,
	LINE_VALUE_USD,
	DISCOUNT_PCT,
	NET_VALUE_USD,
	REQUESTED_DELIVERY_DATE,
	COMMITTED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	DELIVERY_VARIANCE_DAYS,
	IS_ON_TIME,
	IS_IN_FULL,
	IS_OTIF,
	FILL_RATE_PCT,
	SHIP_TO_REGION,
	SHIP_TO_COUNTRY,
	SHIPPING_METHOD,
	SHIPMENT_REF,
	FREIGHT_CHARGE_USD,
	SERVICE_LEVEL,
	PRIORITY,
	SALES_REP_EMAIL,
	CHANNEL,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    order_number,
    order_header_id,
    line_item,
    order_date::DATE AS order_date,
    UPPER(TRIM(order_type)) AS order_type,
    UPPER(TRIM(order_status)) AS order_status,
    UPPER(TRIM(customer_id)) AS customer_id,
    UPPER(TRIM(shipping_plant)) AS plant_code,
    UPPER(TRIM(material_number)) AS material_number,
    GREATEST(ordered_qty, 0) AS ordered_qty,
    GREATEST(shipped_qty, 0) AS shipped_qty,
    GREATEST(delivered_qty, 0) AS delivered_qty,
    UPPER(TRIM(uom)) AS uom,
    unit_price_usd,
    ROUND(ordered_qty * unit_price_usd, 2) AS line_value_usd,
    discount_pct,
    ROUND(ordered_qty * unit_price_usd * (1 - COALESCE(discount_pct, 0) / 100), 2) AS net_value_usd,
    requested_delivery_date::DATE AS requested_delivery_date,
    committed_delivery_date::DATE AS committed_delivery_date,
    actual_delivery_date::DATE AS actual_delivery_date,
    -- Standardized OTD logic (same formula as POs)
    DATEDIFF(DAY, committed_delivery_date, actual_delivery_date) AS delivery_variance_days,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= committed_delivery_date THEN TRUE ELSE FALSE END AS is_on_time,
    CASE WHEN delivered_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_in_full,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= committed_delivery_date AND delivered_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_otif,
    DIV0(delivered_qty, ordered_qty) * 100 AS fill_rate_pct,
    UPPER(TRIM(ship_to_region)) AS ship_to_region,
    UPPER(TRIM(ship_to_country)) AS ship_to_country,
    UPPER(TRIM(shipping_method)) AS shipping_method,
    shipment_ref,
    freight_charge_usd,
    UPPER(TRIM(service_level)) AS service_level,
    UPPER(TRIM(priority)) AS priority,
    sales_rep_email,
    UPPER(TRIM(channel)) AS channel,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_SHIPMENTS(
	SHIPMENT_ID,
	BILL_OF_LADING,
	SHIP_DATE,
	ESTIMATED_ARRIVAL,
	ACTUAL_ARRIVAL,
	SHIPMENT_STATUS,
	TRANSPORT_MODE,
	CARRIER_NAME,
	CARRIER_CODE,
	ORIGIN_PLANT,
	ORIGIN_PORT,
	DESTINATION_PLANT,
	DESTINATION_PORT,
	ORIGIN_REGION,
	DESTINATION_REGION,
	GROSS_WEIGHT_KG,
	VOLUME_CBM,
	PACKAGE_COUNT,
	PACKAGE_TYPE,
	FREIGHT_COST_USD,
	INSURANCE_COST_USD,
	CUSTOMS_DUTY_USD,
	HANDLING_CHARGES_USD,
	TOTAL_LOGISTICS_COST_USD,
	INCOTERM,
	TRANSIT_EXCEPTIONS_COUNT,
	EXCEPTION_TYPE,
	CO2_EMISSIONS_KG,
	IS_ON_TIME,
	DELAY_DAYS,
	REFERENCE_PO,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    shipment_id,
    bill_of_lading,
    ship_date::DATE AS ship_date,
    estimated_arrival::DATE AS estimated_arrival,
    actual_arrival::DATE AS actual_arrival,
    UPPER(TRIM(shipment_status)) AS shipment_status,
    UPPER(TRIM(transport_mode)) AS transport_mode,
    UPPER(TRIM(carrier_name)) AS carrier_name,
    UPPER(TRIM(carrier_code)) AS carrier_code,
    UPPER(TRIM(origin_plant)) AS origin_plant,
    UPPER(TRIM(origin_port)) AS origin_port,
    UPPER(TRIM(destination_plant)) AS destination_plant,
    UPPER(TRIM(destination_port)) AS destination_port,
    UPPER(TRIM(origin_region)) AS origin_region,
    UPPER(TRIM(destination_region)) AS destination_region,
    GREATEST(gross_weight_kg, 0) AS gross_weight_kg,
    GREATEST(volume_cbm, 0) AS volume_cbm,
    GREATEST(package_count, 0) AS package_count,
    UPPER(TRIM(package_type)) AS package_type,
    freight_cost_usd,
    insurance_cost_usd,
    customs_duty_usd,
    handling_charges_usd,
    ROUND(COALESCE(freight_cost_usd,0) + COALESCE(insurance_cost_usd,0) + COALESCE(customs_duty_usd,0) + COALESCE(handling_charges_usd,0), 2) AS total_logistics_cost_usd,
    UPPER(TRIM(incoterm)) AS incoterm,
    transit_exceptions_count,
    UPPER(TRIM(exception_type)) AS exception_type,
    co2_emissions_kg,
    CASE WHEN actual_arrival IS NOT NULL AND actual_arrival <= estimated_arrival THEN TRUE ELSE FALSE END AS is_on_time,
    CASE WHEN actual_arrival IS NOT NULL THEN DATEDIFF(DAY, estimated_arrival, actual_arrival) ELSE NULL END AS delay_days,
    reference_po,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L2_STAGE.STG_SUPPLIER_PERFORMANCE(
	RECORD_ID,
	SUPPLIER_ID,
	EVALUATION_DATE,
	PERIOD_START,
	PERIOD_END,
	REVIEW_TYPE,
	TOTAL_POS_IN_PERIOD,
	ON_TIME_DELIVERIES,
	OTD_PCT,
	IN_FULL_DELIVERIES,
	OTIF_PCT,
	QUALITY_INCIDENTS,
	DEFECT_PPM,
	QUALITY_SCORE,
	RESPONSIVENESS_SCORE,
	COST_SCORE,
	INNOVATION_SCORE,
	SUSTAINABILITY_SCORE,
	COMPOSITE_SCORE,
	GRADE,
	NCR_COUNT,
	CORRECTIVE_ACTIONS_OPEN,
	CORRECTIVE_ACTIONS_CLOSED,
	AVG_LEAD_TIME_DAYS,
	LEAD_TIME_VARIANCE_DAYS,
	RECOMMENDATION,
	_LOADED_AT,
	_SOURCE_SYSTEM,
	_STAGED_AT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    record_id,
    UPPER(TRIM(supplier_id)) AS supplier_id,
    evaluation_date::DATE AS evaluation_date,
    period_start::DATE AS period_start,
    period_end::DATE AS period_end,
    UPPER(TRIM(review_type)) AS review_type,
    total_pos_in_period,
    on_time_deliveries,
    ROUND(DIV0(on_time_deliveries, total_pos_in_period) * 100, 2) AS otd_pct,
    in_full_deliveries,
    ROUND(DIV0(in_full_deliveries, total_pos_in_period) * 100, 2) AS otif_pct,
    quality_incidents,
    defect_ppm,
    quality_score,
    responsiveness_score,
    cost_score,
    innovation_score,
    sustainability_score,
    ROUND(quality_score * 0.3 + responsiveness_score * 0.2 + cost_score * 0.2 + DIV0(on_time_deliveries, GREATEST(total_pos_in_period, 1)) * 10 * 0.2 + innovation_score * 0.1, 2) AS composite_score,
    CASE
        WHEN composite_score >= 8 THEN 'A'
        WHEN composite_score >= 6 THEN 'B'
        WHEN composite_score >= 4 THEN 'C'
        ELSE 'D'
    END AS grade,
    ncr_count,
    corrective_actions_open,
    corrective_actions_closed,
    avg_lead_time_days,
    lead_time_variance_days,
    UPPER(TRIM(recommendation)) AS recommendation,
    _loaded_at,
    _source_system,
    CURRENT_TIMESTAMP() AS _staged_at
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_SRM_SUPPLIER_PERFORMANCE;
