-- L5 Core: fact and dimension Dynamic Tables and the ontology
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- dbt marts live in dbt_project/models/marts.
USE DATABASE ZERO_TO_ONE_CHAIN;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.DIM_CUSTOMER(
	CUSTOMER_ID,
	CUSTOMER_NAME,
	REGION,
	COUNTRY,
	INDUSTRY,
	SEGMENT,
	SERVICE_TIER,
	ANNUAL_REVENUE_USD_MM,
	ANNUAL_ORDER_VALUE_USD_MM,
	CUSTOMER_STATUS,
	RELATIONSHIP_START_DATE,
	PAYMENT_TERMS,
	BILLING_CURRENCY,
	NUM_SHIP_TO_LOCATIONS,
	CREDIT_RISK,
	NPS_SCORE,
	HISTORICAL_FILL_RATE_PCT,
	HISTORICAL_OTD_PCT,
	SLA_CONTRACT,
	SLA_TARGET_OTD_PCT,
	CHANNEL,
	OPEN_COMPLAINTS
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    customer_id,
    customer_name,
    customer_region AS region,
    country,
    industry,
    segment,
    service_tier,
    annual_revenue_usd_mm,
    annual_order_value_usd_mm,
    customer_status,
    relationship_start_date,
    payment_terms,
    billing_currency,
    num_ship_to_locations,
    credit_risk,
    nps_score,
    historical_fill_rate_pct,
    historical_otd_pct,
    sla_contract,
    sla_target_otd_pct,
    channel,
    open_complaints
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.DIM_PART(
	PART_ID,
	PART_NAME,
	PART_TYPE,
	PART_GROUP,
	CATEGORY,
	FAMILY,
	UOM,
	STANDARD_COST_USD,
	WEIGHT_KG,
	ABC_CLASS,
	XYZ_CLASS,
	SAFETY_STOCK_DAYS,
	LEAD_TIME_DAYS,
	MIN_ORDER_QTY,
	ECONOMIC_ORDER_QTY,
	LIFECYCLE_STATUS,
	HAZARDOUS,
	SPECIAL_HANDLING,
	DUAL_SOURCED,
	PRIMARY_SUPPLIER_ID,
	SECONDARY_SUPPLIER_ID,
	CREATED_DATE,
	LAST_MODIFIED_DATE
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    material_number AS part_id,
    material_description AS part_name,
    material_type AS part_type,
    material_group AS part_group,
    category,
    family,
    uom,
    standard_cost_usd,
    weight_kg,
    abc_class,
    xyz_class,
    safety_stock_days,
    lead_time_days,
    min_order_qty,
    economic_order_qty,
    lifecycle_status,
    hazardous,
    special_handling,
    dual_sourced,
    primary_vendor_code AS primary_supplier_id,
    secondary_vendor_code AS secondary_supplier_id,
    created_date,
    last_modified_date
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_MATERIALS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.DIM_PLANT(
	PLANT_ID,
	PLANT_NAME,
	COUNTRY,
	REGION,
	PLANT_TYPE,
	PLANT_STATUS,
	HEADCOUNT,
	CAPACITY_SQM,
	UTILIZATION_PCT,
	LATITUDE,
	LONGITUDE,
	CERTIFICATIONS,
	ESTABLISHED_DATE,
	ANNUAL_OUTPUT_VALUE_USD_MM,
	PRIMARY_SECTOR,
	NUM_PRODUCTION_LINES,
	SHIFT_PATTERN,
	ENERGY_COST_PER_UNIT,
	ENERGY_SOURCE
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    plant_code AS plant_id,
    plant_name,
    country,
    region,
    plant_type,
    plant_status,
    headcount,
    capacity_sqm,
    utilization_pct,
    latitude,
    longitude,
    certifications,
    established_date,
    annual_output_value_usd_mm,
    primary_sector,
    num_production_lines,
    shift_pattern,
    energy_cost_per_unit,
    energy_source
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PLANTS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.DIM_SUPPLIER(
	SUPPLIER_ID,
	SUPPLIER_NAME,
	REGION,
	COUNTRY,
	TIER,
	ERP_STATUS,
	SRM_TIER,
	PRIMARY_CATEGORY,
	CERTIFICATIONS,
	ONBOARDING_DATE,
	ANNUAL_SPEND_USD_MM,
	LEAD_TIME_DAYS,
	OTD_PCT,
	DEFECT_PPM,
	FINANCIAL_RISK_SCORE,
	GEOPOLITICAL_RISK_SCORE,
	QUALITY_SCORE,
	DELIVERY_RELIABILITY_PCT,
	RESPONSIVENESS_SCORE,
	INNOVATION_SCORE,
	SUSTAINABILITY_SCORE,
	COST_COMPETITIVENESS_IDX,
	ESG_COMPLIANCE_STATUS,
	CARBON_INTENSITY_SCORE,
	CONCENTRATION_RISK,
	BLENDED_RISK_SCORE,
	ENTITY_RESOLUTION_CONFIDENCE,
	PAYMENT_TERMS,
	COMPANY_SIZE,
	EMPLOYEE_COUNT,
	DUAL_SOURCE_AVAILABLE,
	LAST_AUDIT_DATE,
	LAST_AUDIT_RESULT
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    canonical_id AS supplier_id,
    canonical_name AS supplier_name,
    region,
    country,
    tier,
    erp_status,
    srm_tier,
    primary_category,
    certifications,
    onboarding_date,
    annual_spend_usd_mm,
    erp_lead_time_days AS lead_time_days,
    erp_otd_pct AS otd_pct,
    erp_defect_ppm AS defect_ppm,
    financial_risk_score,
    geopolitical_risk_score,
    srm_quality_score AS quality_score,
    srm_delivery_pct AS delivery_reliability_pct,
    srm_responsiveness AS responsiveness_score,
    srm_innovation AS innovation_score,
    srm_sustainability AS sustainability_score,
    srm_cost_idx AS cost_competitiveness_idx,
    esg_compliance_status,
    carbon_intensity_score,
    concentration_risk,
    blended_risk_score,
    match_confidence AS entity_resolution_confidence,
    payment_terms,
    company_size,
    employee_count,
    dual_source_available,
    last_audit_date,
    last_audit_result
FROM ZERO_TO_ONE_CHAIN.L4_HARMONIZE.GOLDEN_SUPPLIERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.FACT_INVENTORY(
	SNAPSHOT_DATE,
	PLANT_CODE,
	MATERIAL_NUMBER,
	STORAGE_LOCATION,
	STORAGE_TYPE,
	ON_HAND_QTY,
	ALLOCATED_QTY,
	AVAILABLE_QTY,
	IN_TRANSIT_QTY,
	ON_ORDER_QTY,
	QUARANTINE_QTY,
	UNIT_COST_USD,
	INVENTORY_VALUE_USD,
	REORDER_POINT,
	SAFETY_STOCK_QTY,
	STOCK_STATUS,
	DAYS_ON_HAND,
	ABC_CLASS,
	TURNOVER_RATIO,
	OBSOLESCENCE_RISK_PCT,
	VALUATION_METHOD,
	LAST_RECEIPT_DATE,
	LAST_ISSUE_DATE,
	COUNT_ACCURACY_PCT,
	LAST_CYCLE_COUNT_DATE,
	CARRYING_COST_USD_DAILY
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    snapshot_date, plant_code, material_number, storage_location, storage_type,
    on_hand_qty, allocated_qty, available_qty, in_transit_qty, on_order_qty, quarantine_qty,
    unit_cost_usd, inventory_value_usd, reorder_point, safety_stock_qty, stock_status,
    days_on_hand, abc_class, turnover_ratio, obsolescence_risk_pct, valuation_method,
    last_receipt_date, last_issue_date, count_accuracy_pct, last_cycle_count_date,
    carrying_cost_usd_daily
FROM ZERO_TO_ONE_CHAIN.L2_STAGE.STG_INVENTORY;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.FACT_ORDERS(
	ORDER_NUMBER,
	ORDER_HEADER_ID,
	LINE_ITEM,
	ORDER_DATE,
	ORDER_TYPE,
	ORDER_STATUS,
	CUSTOMER_ID,
	PLANT_CODE,
	MATERIAL_NUMBER,
	ORDERED_QTY,
	SHIPPED_QTY,
	DELIVERED_QTY,
	UOM,
	UNIT_PRICE_USD,
	LINE_VALUE_USD,
	DISCOUNT_PCT,
	NET_VALUE_USD,
	REQUESTED_DELIVERY_DATE,
	COMMITTED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	DELIVERY_VARIANCE_DAYS,
	IS_ON_TIME,
	IS_IN_FULL,
	IS_OTIF,
	FILL_RATE_PCT,
	SHIP_TO_REGION,
	SHIP_TO_COUNTRY,
	SHIPPING_METHOD,
	SHIPMENT_REF,
	FREIGHT_CHARGE_USD,
	SERVICE_LEVEL,
	PRIORITY,
	CHANNEL
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    order_number, order_header_id, line_item, order_date, order_type, order_status,
    customer_id, plant_code, material_number, ordered_qty, shipped_qty, delivered_qty, uom,
    unit_price_usd, line_value_usd, discount_pct, net_value_usd,
    requested_delivery_date, committed_delivery_date, actual_delivery_date,
    delivery_variance_days, is_on_time, is_in_full, is_otif, fill_rate_pct,
    ship_to_region, ship_to_country, shipping_method, shipment_ref, freight_charge_usd,
    service_level, priority, channel
FROM ZERO_TO_ONE_CHAIN.L2_STAGE.STG_SALES_ORDERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.FACT_PURCHASE_ORDERS(
	PO_NUMBER,
	PO_HEADER_ID,
	LINE_NUMBER,
	PO_DATE,
	PO_TYPE,
	PO_STATUS,
	SUPPLIER_ID,
	PLANT_CODE,
	MATERIAL_NUMBER,
	MATERIAL_GROUP,
	ORDERED_QTY,
	RECEIVED_QTY,
	REJECTED_QTY,
	UOM,
	UNIT_PRICE_USD,
	EXTENDED_PRICE_USD,
	DISCOUNT_PCT,
	FREIGHT_COST_USD,
	DUTY_COST_USD,
	HANDLING_COST_USD,
	LANDED_COST_USD,
	REQUESTED_DELIVERY_DATE,
	CONFIRMED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	DELIVERY_VARIANCE_DAYS,
	IS_ON_TIME,
	IS_IN_FULL,
	IS_OTIF,
	PRIORITY,
	ORDER_SOURCE,
	COST_CENTER,
	PROJECT_CODE
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    po_number, po_header_id, line_number, po_date, po_type, po_status,
    vendor_code AS supplier_id, plant_code, material_number, material_group,
    ordered_qty, received_qty, rejected_qty, uom,
    unit_price_usd, extended_price_usd, discount_pct,
    freight_cost_usd, duty_cost_usd, handling_cost_usd, landed_cost_usd,
    requested_delivery_date, confirmed_delivery_date, actual_delivery_date,
    delivery_variance_days, is_on_time, is_in_full, is_otif,
    priority, order_source, cost_center, project_code
FROM ZERO_TO_ONE_CHAIN.L2_STAGE.STG_PURCHASE_ORDERS;

create or replace dynamic table ZERO_TO_ONE_CHAIN.L5_CORE.FACT_SHIPMENTS(
	SHIPMENT_ID,
	BILL_OF_LADING,
	SHIP_DATE,
	ESTIMATED_ARRIVAL,
	ACTUAL_ARRIVAL,
	SHIPMENT_STATUS,
	TRANSPORT_MODE,
	CARRIER_NAME,
	CARRIER_CODE,
	ORIGIN_PLANT,
	ORIGIN_PORT,
	DESTINATION_PLANT,
	DESTINATION_PORT,
	ORIGIN_REGION,
	DESTINATION_REGION,
	GROSS_WEIGHT_KG,
	VOLUME_CBM,
	PACKAGE_COUNT,
	PACKAGE_TYPE,
	FREIGHT_COST_USD,
	INSURANCE_COST_USD,
	CUSTOMS_DUTY_USD,
	HANDLING_CHARGES_USD,
	TOTAL_LOGISTICS_COST_USD,
	INCOTERM,
	TRANSIT_EXCEPTIONS_COUNT,
	EXCEPTION_TYPE,
	CO2_EMISSIONS_KG,
	IS_ON_TIME,
	DELAY_DAYS,
	REFERENCE_PO
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = Z21_WH
 as
SELECT
    shipment_id, bill_of_lading, ship_date, estimated_arrival, actual_arrival,
    shipment_status, transport_mode, carrier_name, carrier_code,
    origin_plant, origin_port, destination_plant, destination_port,
    origin_region, destination_region,
    gross_weight_kg, volume_cbm, package_count, package_type,
    freight_cost_usd, insurance_cost_usd, customs_duty_usd, handling_charges_usd,
    total_logistics_cost_usd, incoterm,
    transit_exceptions_count, exception_type, co2_emissions_kg,
    is_on_time, delay_days, reference_po
FROM ZERO_TO_ONE_CHAIN.L2_STAGE.STG_SHIPMENTS;

create or replace TABLE ZERO_TO_ONE_CHAIN.L5_CORE.ONTOLOGY_EDGES (
	EDGE_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	FROM_ENTITY_TYPE VARCHAR(16777216) NOT NULL,
	FROM_ENTITY_ID VARCHAR(16777216) NOT NULL,
	RELATIONSHIP VARCHAR(16777216) NOT NULL,
	TO_ENTITY_TYPE VARCHAR(16777216) NOT NULL,
	TO_ENTITY_ID VARCHAR(16777216) NOT NULL,
	WEIGHT NUMBER(10,4) DEFAULT 1,
	VALID_FROM DATE DEFAULT CURRENT_DATE(),
	VALID_TO DATE,
	METADATA VARIANT
);
