-- Staged sales orders: standardized OTD/OTIF/fill rate definitions
{{ config(materialized='view') }}

SELECT
    order_number,
    order_header_id,
    line_item,
    order_date::DATE AS order_date,
    UPPER(TRIM(order_type)) AS order_type,
    UPPER(TRIM(order_status)) AS order_status,
    UPPER(TRIM(customer_id)) AS customer_id,
    UPPER(TRIM(shipping_plant)) AS plant_code,
    UPPER(TRIM(material_number)) AS material_number,
    GREATEST(ordered_qty, 0) AS ordered_qty,
    GREATEST(shipped_qty, 0) AS shipped_qty,
    GREATEST(delivered_qty, 0) AS delivered_qty,
    UPPER(TRIM(uom)) AS uom,
    unit_price_usd,
    ROUND(ordered_qty * unit_price_usd, 2) AS line_value_usd,
    discount_pct,
    ROUND(ordered_qty * unit_price_usd * (1 - COALESCE(discount_pct, 0) / 100), 2) AS net_value_usd,
    requested_delivery_date::DATE AS requested_delivery_date,
    committed_delivery_date::DATE AS committed_delivery_date,
    actual_delivery_date::DATE AS actual_delivery_date,
    DATEDIFF(DAY, committed_delivery_date, actual_delivery_date) AS delivery_variance_days,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= committed_delivery_date THEN TRUE ELSE FALSE END AS is_on_time,
    CASE WHEN delivered_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_in_full,
    CASE WHEN actual_delivery_date IS NOT NULL AND actual_delivery_date <= committed_delivery_date AND delivered_qty >= ordered_qty THEN TRUE ELSE FALSE END AS is_otif,
    DIV0(delivered_qty, ordered_qty) * 100 AS fill_rate_pct,
    UPPER(TRIM(ship_to_region)) AS ship_to_region,
    UPPER(TRIM(ship_to_country)) AS ship_to_country,
    UPPER(TRIM(shipping_method)) AS shipping_method,
    shipment_ref,
    freight_charge_usd,
    UPPER(TRIM(service_level)) AS service_level,
    UPPER(TRIM(priority)) AS priority,
    UPPER(TRIM(channel)) AS channel,
    _loaded_at,
    _source_system
FROM {{ source('raw_erp', 'RAW_ERP_SALES_ORDERS') }}
