-- L6 Semantic: the governed semantic view with canonical metrics
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- Source of truth for editing: cortex_project/SUPPLY_CHAIN_ANALYTICS.sv.yaml.
USE DATABASE ZERO_TO_ONE_CHAIN;

create or replace semantic view SUPPLY_CHAIN_ANALYTICS
	tables (
		ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY,
		ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_LANDED_COST,
		ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD,
		ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_SUPPLIER_RISK primary key (SUPPLIER_ID)
	)
	facts (
		VW_METRIC_INVENTORY.CARRYING_COST_USD_DAILY as CARRYING_COST_USD_DAILY,
		VW_METRIC_INVENTORY.DAYS_OF_INVENTORY as DAYS_OF_INVENTORY,
		VW_METRIC_INVENTORY.INVENTORY_VALUE_USD as INVENTORY_VALUE_USD,
		VW_METRIC_INVENTORY.OBSOLESCENCE_RISK_PCT as OBSOLESCENCE_RISK_PCT,
		VW_METRIC_INVENTORY.TURNOVER_RATIO as TURNOVER_RATIO,
		VW_METRIC_LANDED_COST.DUTY_COST_USD as DUTY_COST_USD,
		VW_METRIC_LANDED_COST.EXTENDED_PRICE_USD as EXTENDED_PRICE_USD,
		VW_METRIC_LANDED_COST.FREIGHT_COST_USD as FREIGHT_COST_USD,
		VW_METRIC_LANDED_COST.HANDLING_COST_USD as HANDLING_COST_USD,
		VW_METRIC_LANDED_COST.LANDED_COST_PER_UNIT_USD as LANDED_COST_PER_UNIT_USD,
		VW_METRIC_LANDED_COST.LANDED_COST_USD as LANDED_COST_USD,
		VW_METRIC_LANDED_COST.UNIT_PRICE_USD as UNIT_PRICE_USD,
		VW_METRIC_OTD.FILL_RATE_PCT as FILL_RATE_PCT,
		VW_METRIC_OTD.NET_VALUE_USD as NET_VALUE_USD,
		VW_METRIC_SUPPLIER_RISK.ANNUAL_SPEND_USD_MM as ANNUAL_SPEND_USD_MM,
		VW_METRIC_SUPPLIER_RISK.BLENDED_RISK_SCORE as BLENDED_RISK_SCORE,
		VW_METRIC_SUPPLIER_RISK.DEFECT_PPM as DEFECT_PPM,
		VW_METRIC_SUPPLIER_RISK.DELIVERY_RELIABILITY_PCT as DELIVERY_RELIABILITY_PCT,
		VW_METRIC_SUPPLIER_RISK.FINANCIAL_RISK_SCORE as FINANCIAL_RISK_SCORE,
		VW_METRIC_SUPPLIER_RISK.GEOPOLITICAL_RISK_SCORE as GEOPOLITICAL_RISK_SCORE,
		VW_METRIC_SUPPLIER_RISK.OTD_PCT as OTD_PCT,
		VW_METRIC_SUPPLIER_RISK.QUALITY_SCORE as QUALITY_SCORE,
		VW_METRIC_SUPPLIER_RISK.SUPPLIER_RISK_SCORE as SUPPLIER_RISK_SCORE,
		VW_METRIC_SUPPLIER_RISK.SUSTAINABILITY_SCORE as SUSTAINABILITY_SCORE
	)
	dimensions (
		VW_METRIC_INVENTORY.ABC_CLASS as ABC_CLASS,
		VW_METRIC_INVENTORY.AVAILABLE_QTY as AVAILABLE_QTY,
		VW_METRIC_INVENTORY.CATEGORY as CATEGORY,
		VW_METRIC_INVENTORY.DAYS_ON_HAND as DAYS_ON_HAND,
		VW_METRIC_INVENTORY.FAMILY as FAMILY,
		VW_METRIC_INVENTORY.IN_TRANSIT_QTY as IN_TRANSIT_QTY,
		VW_METRIC_INVENTORY.MATERIAL_NUMBER as MATERIAL_NUMBER,
		VW_METRIC_INVENTORY.ON_HAND_QTY as ON_HAND_QTY,
		VW_METRIC_INVENTORY.ON_ORDER_QTY as ON_ORDER_QTY,
		VW_METRIC_INVENTORY.PART_NAME as PART_NAME,
		VW_METRIC_INVENTORY.PLANT_CODE as PLANT_CODE,
		VW_METRIC_INVENTORY.PLANT_NAME as PLANT_NAME,
		VW_METRIC_INVENTORY.QUARANTINE_QTY as QUARANTINE_QTY,
		VW_METRIC_INVENTORY.REGION as REGION,
		VW_METRIC_INVENTORY.REORDER_POINT as REORDER_POINT,
		VW_METRIC_INVENTORY.SAFETY_STOCK_QTY as SAFETY_STOCK_QTY,
		VW_METRIC_INVENTORY.STOCK_STATUS as STOCK_STATUS,
		VW_METRIC_INVENTORY.SNAPSHOT_DATE as SNAPSHOT_DATE,
		VW_METRIC_INVENTORY.SNAPSHOT_MONTH as SNAPSHOT_MONTH,
		VW_METRIC_LANDED_COST.IS_ON_TIME as IS_ON_TIME,
		VW_METRIC_LANDED_COST.IS_OTIF as IS_OTIF,
		VW_METRIC_LANDED_COST.MATERIAL_GROUP as MATERIAL_GROUP,
		VW_METRIC_LANDED_COST.MATERIAL_NUMBER as MATERIAL_NUMBER,
		VW_METRIC_LANDED_COST.ORDERED_QTY as ORDERED_QTY,
		VW_METRIC_LANDED_COST.PLANT_CODE as PLANT_CODE,
		VW_METRIC_LANDED_COST.SUPPLIER_COUNTRY as SUPPLIER_COUNTRY,
		VW_METRIC_LANDED_COST.SUPPLIER_ID as SUPPLIER_ID,
		VW_METRIC_LANDED_COST.SUPPLIER_NAME as SUPPLIER_NAME,
		VW_METRIC_LANDED_COST.SUPPLIER_REGION as SUPPLIER_REGION,
		VW_METRIC_LANDED_COST.PO_DATE as PO_DATE,
		VW_METRIC_LANDED_COST.PO_MONTH as PO_MONTH,
		VW_METRIC_OTD.CHANNEL as CHANNEL,
		VW_METRIC_OTD.CUSTOMER_ID as CUSTOMER_ID,
		VW_METRIC_OTD.CUSTOMER_NAME as CUSTOMER_NAME,
		VW_METRIC_OTD.CUSTOMER_REGION as CUSTOMER_REGION with synonyms=('region','market') comment='Customer region: AMERICAS, EMEA, APAC.',
		VW_METRIC_OTD.DELIVERED_QTY as DELIVERED_QTY,
		VW_METRIC_OTD.DELIVERY_VARIANCE_DAYS as DELIVERY_VARIANCE_DAYS,
		VW_METRIC_OTD.INDUSTRY as INDUSTRY,
		VW_METRIC_OTD.IS_IN_FULL as IS_IN_FULL,
		VW_METRIC_OTD.IS_ON_TIME as IS_ON_TIME comment='TRUE if delivered on or before the committed date. NULL for lines not yet delivered.',
		VW_METRIC_OTD.IS_OTIF as IS_OTIF comment='TRUE if delivered on time AND in full. NULL for lines not yet delivered.',
		VW_METRIC_OTD.MATERIAL_NUMBER as MATERIAL_NUMBER,
		VW_METRIC_OTD.ORDERED_QTY as ORDERED_QTY,
		VW_METRIC_OTD.PLANT_CODE as PLANT_CODE,
		VW_METRIC_OTD.PLANT_NAME as PLANT_NAME,
		VW_METRIC_OTD.PLANT_REGION as PLANT_REGION,
		VW_METRIC_OTD.PRIORITY as PRIORITY,
		VW_METRIC_OTD.SEGMENT as SEGMENT,
		VW_METRIC_OTD.SERVICE_LEVEL as SERVICE_LEVEL,
		VW_METRIC_OTD.SHIPPING_METHOD as SHIPPING_METHOD,
		VW_METRIC_OTD.IS_DELIVERED as IS_DELIVERED comment='TRUE when the order line has an actual delivery date. OTD, OTIF and fill rate are only measured on delivered lines.',
		VW_METRIC_OTD.SERVICE_TIER as SERVICE_TIER with synonyms=('customer tier') comment='Customer service tier: Platinum, Gold, Silver, Bronze, Standard.',
		VW_METRIC_OTD.ORDER_NUMBER as ORDER_NUMBER comment='Sales order line identifier.',
		VW_METRIC_OTD.ORDER_DATE as ORDER_DATE,
		VW_METRIC_OTD.ORDER_MONTH as ORDER_MONTH,
		VW_METRIC_OTD.ORDER_QUARTER as ORDER_QUARTER,
		VW_METRIC_OTD.ACTUAL_DELIVERY_DATE as ACTUAL_DELIVERY_DATE with synonyms=('delivery date') comment='Date the line was delivered. Use this for monthly/quarterly OTD trends.',
		VW_METRIC_OTD.COMMITTED_DELIVERY_DATE as COMMITTED_DELIVERY_DATE with synonyms=('promise date','commit date') comment='Date promised to the customer.',
		VW_METRIC_SUPPLIER_RISK.CONCENTRATION_RISK as CONCENTRATION_RISK,
		VW_METRIC_SUPPLIER_RISK.COUNTRY as COUNTRY,
		VW_METRIC_SUPPLIER_RISK.DUAL_SOURCE_AVAILABLE as DUAL_SOURCE_AVAILABLE,
		VW_METRIC_SUPPLIER_RISK.ESG_COMPLIANCE_STATUS as ESG_COMPLIANCE_STATUS,
		VW_METRIC_SUPPLIER_RISK.LAST_AUDIT_RESULT as LAST_AUDIT_RESULT,
		VW_METRIC_SUPPLIER_RISK.LEAD_TIME_DAYS as LEAD_TIME_DAYS,
		VW_METRIC_SUPPLIER_RISK.PRIMARY_CATEGORY as PRIMARY_CATEGORY,
		VW_METRIC_SUPPLIER_RISK.REGION as REGION,
		VW_METRIC_SUPPLIER_RISK.SUPPLIER_ID as SUPPLIER_ID,
		VW_METRIC_SUPPLIER_RISK.SUPPLIER_NAME as SUPPLIER_NAME,
		VW_METRIC_SUPPLIER_RISK.TIER as TIER
	)
	metrics (
		VW_METRIC_OTD.OTD_PCT as AVG(IS_ON_TIME::INT) * 100 with synonyms=('on-time delivery','OTD','on time rate','delivery performance') comment='CANONICAL On-Time Delivery %: share of DELIVERED order lines delivered on or before the committed date. Target 95%.',
		VW_METRIC_OTD.OTIF_PCT as AVG(IS_OTIF::INT) * 100 with synonyms=('on time in full','OTIF') comment='CANONICAL OTIF %: share of DELIVERED order lines delivered on time and in full. Target 90%.',
		VW_METRIC_OTD.FILL_RATE as AVG(FILL_RATE_PCT) with synonyms=('fill rate','in full rate') comment='CANONICAL Fill Rate %: delivered quantity / ordered quantity, averaged over delivered lines. Target 98%.',
		VW_METRIC_OTD.DELIVERED_LINES as COUNT_IF(IS_DELIVERED) comment='Number of delivered order lines.',
		VW_METRIC_OTD.TOTAL_ORDER_VALUE as SUM(NET_VALUE_USD) with synonyms=('revenue','sales') comment='Net order value in USD.'
	)
	comment='Supply Chain Decision Twin analytics model for Zero to One Chain. Provides canonical metric definitions for On-Time Delivery (OTD), OTIF, Fill Rate, Days of Inventory (DOI), Landed Cost, and Supplier Risk Score. Every persona (Planning, Procurement, Logistics) gets the same answer for the same question. Data flows through a 9-layer architecture from raw ingestion to governed semantic views.'
	ai_verified_queries (
		"0;1" AS ( 
QUESTION 'Which are the top 10 riskiest suppliers?' 
ONBOARDING_QUESTION false
SQL 'SELECT SUPPLIER_NAME, SUPPLIER_RISK_SCORE, OTD_PCT, DEFECT_PPM, CONCENTRATION_RISK FROM vw_metric_supplier_risk ORDER BY SUPPLIER_RISK_SCORE DESC LIMIT 10'),
		"1;1" AS ( 
QUESTION 'What is the average landed cost per unit by material group?' 
ONBOARDING_QUESTION false
SQL 'SELECT MATERIAL_GROUP, ROUND(AVG(LANDED_COST_PER_UNIT_USD), 2) AS avg_landed_cost FROM vw_metric_landed_cost GROUP BY MATERIAL_GROUP ORDER BY avg_landed_cost DESC'),
		"2;1" AS ( 
QUESTION 'What is the average days of inventory by region?' 
ONBOARDING_QUESTION false
SQL 'SELECT REGION, ROUND(AVG(DAYS_OF_INVENTORY), 1) AS avg_doi FROM vw_metric_inventory GROUP BY REGION ORDER BY avg_doi DESC'),
		"3;1" AS ( 
QUESTION 'What is the stock status breakdown by plant?' 
ONBOARDING_QUESTION false
SQL 'SELECT PLANT_NAME, STOCK_STATUS, COUNT(*) AS item_count FROM vw_metric_inventory GROUP BY PLANT_NAME, STOCK_STATUS ORDER BY PLANT_NAME, STOCK_STATUS'),
		OTD_BY_INDUSTRY AS ( 
QUESTION 'What is the on-time delivery rate by customer industry?' 
ONBOARDING_QUESTION false
SQL 'SELECT INDUSTRY, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, COUNT(*) AS delivered_lines FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED GROUP BY 1 ORDER BY otd_pct DESC'),
		OTIF_BY_CHANNEL AS ( 
QUESTION 'What is OTIF by sales channel?' 
ONBOARDING_QUESTION false
SQL 'SELECT CHANNEL, ROUND(AVG(IS_OTIF::INT)*100, 1) AS otif_pct FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED GROUP BY 1 ORDER BY otif_pct DESC'),
		TOP_CUSTOMERS_BY_REVENUE AS ( 
QUESTION 'Who are the top 10 customers by order value?' 
ONBOARDING_QUESTION false
SQL 'SELECT CUSTOMER_NAME, CUSTOMER_REGION, ROUND(SUM(NET_VALUE_USD), 2) AS TOTAL_ORDER_VALUE FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD GROUP BY CUSTOMER_NAME, CUSTOMER_REGION ORDER BY TOTAL_ORDER_VALUE DESC LIMIT 10'),
		SUPPLIER_RISK_BY_CATEGORY AS ( 
QUESTION 'What is the average supplier risk score by product category?' 
ONBOARDING_QUESTION false
SQL 'SELECT PRIMARY_CATEGORY, ROUND(AVG(SUPPLIER_RISK_SCORE), 2) AS AVG_RISK, COUNT(*) AS SUPPLIER_COUNT FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_SUPPLIER_RISK GROUP BY PRIMARY_CATEGORY ORDER BY AVG_RISK DESC'),
		CRITICAL_RISK_SUPPLIERS AS ( 
QUESTION 'Which suppliers have critical concentration risk?' 
ONBOARDING_QUESTION false
SQL 'SELECT SUPPLIER_NAME, REGION, SUPPLIER_RISK_SCORE, OTD_PCT, DUAL_SOURCE_AVAILABLE FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_SUPPLIER_RISK WHERE CONCENTRATION_RISK = ''Critical'' ORDER BY SUPPLIER_RISK_SCORE DESC'),
		LANDED_COST_TREND AS ( 
QUESTION 'What is the landed cost per unit trend by month?' 
ONBOARDING_QUESTION false
SQL 'SELECT PO_MONTH, ROUND(AVG(LANDED_COST_PER_UNIT_USD), 2) AS AVG_LANDED_COST FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_LANDED_COST WHERE LANDED_COST_PER_UNIT_USD IS NOT NULL GROUP BY PO_MONTH ORDER BY PO_MONTH'),
		LANDED_COST_BY_SUPPLIER_REGION AS ( 
QUESTION 'What is the average landed cost by supplier region?' 
ONBOARDING_QUESTION false
SQL 'SELECT SUPPLIER_REGION, ROUND(AVG(LANDED_COST_PER_UNIT_USD), 2) AS AVG_COST, ROUND(SUM(LANDED_COST_USD), 0) AS TOTAL_COST FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_LANDED_COST WHERE LANDED_COST_PER_UNIT_USD IS NOT NULL GROUP BY SUPPLIER_REGION ORDER BY AVG_COST DESC'),
		STOCKOUT_ITEMS AS ( 
QUESTION 'Which items are currently stocked out?' 
ONBOARDING_QUESTION false
SQL 'SELECT PLANT_NAME, MATERIAL_NUMBER, PART_NAME, CATEGORY, REGION FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY WHERE STOCK_STATUS = ''STOCKOUT'' ORDER BY PLANT_NAME, MATERIAL_NUMBER'),
		INVENTORY_VALUE_BY_ABC AS ( 
QUESTION 'What is the inventory value breakdown by ABC classification?' 
ONBOARDING_QUESTION false
SQL 'SELECT ABC_CLASS, ROUND(SUM(INVENTORY_VALUE_USD) / 1e6, 2) AS VALUE_MM, COUNT(*) AS ITEM_COUNT, ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DOI FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY GROUP BY ABC_CLASS ORDER BY ABC_CLASS'),
		OBSOLESCENCE_RISK AS ( 
QUESTION 'Which items have the highest obsolescence risk?' 
ONBOARDING_QUESTION false
SQL 'SELECT MATERIAL_NUMBER, PART_NAME, PLANT_NAME, REGION, OBSOLESCENCE_RISK_PCT, INVENTORY_VALUE_USD, DAYS_ON_HAND FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY WHERE OBSOLESCENCE_RISK_PCT > 30 ORDER BY OBSOLESCENCE_RISK_PCT DESC LIMIT 20'),
		OTD_BY_PLANT AS ( 
QUESTION 'What is the on-time delivery rate by plant?' 
ONBOARDING_QUESTION false
SQL 'SELECT PLANT_NAME, PLANT_REGION, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, COUNT(*) AS delivered_lines FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED GROUP BY 1,2 ORDER BY otd_pct'),
		OTD_BY_PRIORITY AS ( 
QUESTION 'Does order priority affect on-time delivery?' 
ONBOARDING_QUESTION false
SQL 'SELECT PRIORITY, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, ROUND(AVG(IS_OTIF::INT)*100, 1) AS otif_pct FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED GROUP BY 1 ORDER BY 1'),
		OTD_BY_SEGMENT AS ( 
QUESTION 'Which customer segment has the worst delivery performance?' 
ONBOARDING_QUESTION false
SQL 'SELECT SEGMENT, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, ROUND(AVG(FILL_RATE_PCT), 1) AS fill_rate FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED GROUP BY 1 ORDER BY otd_pct'),
		NO_DUAL_SOURCE_HIGH_SPEND AS ( 
QUESTION 'Which high-spend suppliers have no backup?' 
ONBOARDING_QUESTION false
SQL 'SELECT SUPPLIER_NAME, REGION, ANNUAL_SPEND_USD_MM, SUPPLIER_RISK_SCORE, CONCENTRATION_RISK FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_SUPPLIER_RISK WHERE DUAL_SOURCE_AVAILABLE = ''No'' AND ANNUAL_SPEND_USD_MM > 20 ORDER BY ANNUAL_SPEND_USD_MM DESC'),
		FREIGHT_COST_BY_MATERIAL_GROUP AS ( 
QUESTION 'What are the total freight costs by material group?' 
ONBOARDING_QUESTION false
SQL 'SELECT MATERIAL_GROUP, ROUND(SUM(FREIGHT_COST_USD), 0) AS TOTAL_FREIGHT, ROUND(AVG(FREIGHT_COST_USD), 2) AS AVG_FREIGHT, COUNT(*) AS PO_COUNT FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_LANDED_COST GROUP BY MATERIAL_GROUP ORDER BY TOTAL_FREIGHT DESC'),
		DOI_BY_PLANT AS ( 
QUESTION 'What are the days of inventory by plant?' 
ONBOARDING_QUESTION false
SQL 'SELECT PLANT_NAME, REGION, ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DOI, ROUND(SUM(INVENTORY_VALUE_USD) / 1e6, 2) AS VALUE_MM FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY WHERE DAYS_OF_INVENTORY IS NOT NULL GROUP BY PLANT_NAME, REGION ORDER BY AVG_DOI DESC'),
		ESG_NON_COMPLIANT_SUPPLIERS AS ( 
QUESTION 'Which suppliers are ESG non-compliant?' 
ONBOARDING_QUESTION false
SQL 'SELECT SUPPLIER_NAME, REGION, ESG_COMPLIANCE_STATUS, SUSTAINABILITY_SCORE, SUPPLIER_RISK_SCORE, ANNUAL_SPEND_USD_MM FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_SUPPLIER_RISK WHERE ESG_COMPLIANCE_STATUS = ''Non-compliant'' ORDER BY ANNUAL_SPEND_USD_MM DESC'),
		APAC_OTD_BY_METHOD AS ( 
QUESTION 'Why did APAC on-time delivery drop?' 
ONBOARDING_QUESTION false
SQL 'SELECT SHIPPING_METHOD, IFF(ORDER_DATE >= ''2026-07-01'', ''Q3 2026'', ''Before Q3'') AS period, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, COUNT(*) AS delivered_lines FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED AND CUSTOMER_REGION = ''APAC'' AND ORDER_DATE >= ''2026-01-01'' GROUP BY 1,2 ORDER BY 1,2'),
		OTD_REGION_QOQ AS ( 
QUESTION 'What is OTD by region last quarter versus the prior quarter?' 
ONBOARDING_QUESTION false
SQL 'SELECT CUSTOMER_REGION, ROUND(AVG(IFF(ACTUAL_DELIVERY_DATE >= ''2026-07-01'', IS_ON_TIME::INT, NULL))*100, 1) AS q3_otd, ROUND(AVG(IFF(ACTUAL_DELIVERY_DATE < ''2026-07-01'', IS_ON_TIME::INT, NULL))*100, 1) AS q2_otd FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED AND ACTUAL_DELIVERY_DATE >= ''2026-04-01'' AND ACTUAL_DELIVERY_DATE < ''2026-10-01'' GROUP BY 1 ORDER BY q3_otd'),
		SLA_BREACH_CUSTOMERS AS ( 
QUESTION 'Which Platinum and Gold customers are below 85% OTD this quarter?' 
ONBOARDING_QUESTION false
SQL 'SELECT CUSTOMER_NAME, CUSTOMER_REGION, SERVICE_TIER, ROUND(AVG(IS_ON_TIME::INT)*100, 1) AS otd_pct, COUNT(*) AS delivered_lines FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD WHERE IS_DELIVERED AND ORDER_DATE >= ''2026-07-01'' AND SERVICE_TIER IN (''Platinum'',''Gold'') GROUP BY 1,2,3 HAVING COUNT(*) >= 5 AND AVG(IS_ON_TIME::INT) < 0.85 ORDER BY otd_pct')
	)
	with extension (CA='{"tables":[{"name":"VW_METRIC_INVENTORY","dimensions":[{"name":"ABC_CLASS"},{"name":"AVAILABLE_QTY"},{"name":"CATEGORY"},{"name":"DAYS_ON_HAND"},{"name":"FAMILY"},{"name":"IN_TRANSIT_QTY"},{"name":"MATERIAL_NUMBER"},{"name":"ON_HAND_QTY"},{"name":"ON_ORDER_QTY"},{"name":"PART_NAME"},{"name":"PLANT_CODE"},{"name":"PLANT_NAME"},{"name":"QUARANTINE_QTY"},{"name":"REGION"},{"name":"REORDER_POINT"},{"name":"SAFETY_STOCK_QTY"},{"name":"STOCK_STATUS"}],"facts":[{"name":"CARRYING_COST_USD_DAILY"},{"name":"DAYS_OF_INVENTORY"},{"name":"INVENTORY_VALUE_USD"},{"name":"OBSOLESCENCE_RISK_PCT"},{"name":"TURNOVER_RATIO"}],"time_dimensions":[{"name":"SNAPSHOT_DATE"},{"name":"SNAPSHOT_MONTH"}]},{"name":"VW_METRIC_LANDED_COST","dimensions":[{"name":"IS_ON_TIME"},{"name":"IS_OTIF"},{"name":"MATERIAL_GROUP"},{"name":"MATERIAL_NUMBER"},{"name":"ORDERED_QTY"},{"name":"PLANT_CODE"},{"name":"SUPPLIER_COUNTRY"},{"name":"SUPPLIER_ID"},{"name":"SUPPLIER_NAME"},{"name":"SUPPLIER_REGION"}],"facts":[{"name":"DUTY_COST_USD"},{"name":"EXTENDED_PRICE_USD"},{"name":"FREIGHT_COST_USD"},{"name":"HANDLING_COST_USD"},{"name":"LANDED_COST_PER_UNIT_USD"},{"name":"LANDED_COST_USD"},{"name":"UNIT_PRICE_USD"}],"time_dimensions":[{"name":"PO_DATE"},{"name":"PO_MONTH"}]},{"name":"VW_METRIC_OTD","dimensions":[{"name":"CHANNEL"},{"name":"CUSTOMER_ID"},{"name":"CUSTOMER_NAME"},{"name":"CUSTOMER_REGION"},{"name":"DELIVERED_QTY"},{"name":"DELIVERY_VARIANCE_DAYS"},{"name":"INDUSTRY"},{"name":"IS_IN_FULL"},{"name":"IS_ON_TIME"},{"name":"IS_OTIF"},{"name":"MATERIAL_NUMBER"},{"name":"ORDERED_QTY"},{"name":"PLANT_CODE"},{"name":"PLANT_NAME"},{"name":"PLANT_REGION"},{"name":"PRIORITY"},{"name":"SEGMENT"},{"name":"SERVICE_LEVEL"},{"name":"SHIPPING_METHOD"},{"name":"IS_DELIVERED"},{"name":"SERVICE_TIER"},{"name":"ORDER_NUMBER"}],"facts":[{"name":"FILL_RATE_PCT"},{"name":"NET_VALUE_USD"}],"metrics":[{"name":"OTD_PCT"},{"name":"OTIF_PCT"},{"name":"FILL_RATE"},{"name":"DELIVERED_LINES"},{"name":"TOTAL_ORDER_VALUE"}],"time_dimensions":[{"name":"ORDER_DATE"},{"name":"ORDER_MONTH"},{"name":"ORDER_QUARTER"},{"name":"ACTUAL_DELIVERY_DATE"},{"name":"COMMITTED_DELIVERY_DATE"}]},{"name":"VW_METRIC_SUPPLIER_RISK","dimensions":[{"name":"CONCENTRATION_RISK"},{"name":"COUNTRY"},{"name":"DUAL_SOURCE_AVAILABLE"},{"name":"ESG_COMPLIANCE_STATUS"},{"name":"LAST_AUDIT_RESULT"},{"name":"LEAD_TIME_DAYS"},{"name":"PRIMARY_CATEGORY"},{"name":"REGION"},{"name":"SUPPLIER_ID"},{"name":"SUPPLIER_NAME"},{"name":"TIER"}],"facts":[{"name":"ANNUAL_SPEND_USD_MM"},{"name":"BLENDED_RISK_SCORE"},{"name":"DEFECT_PPM"},{"name":"DELIVERY_RELIABILITY_PCT"},{"name":"FINANCIAL_RISK_SCORE"},{"name":"GEOPOLITICAL_RISK_SCORE"},{"name":"OTD_PCT"},{"name":"QUALITY_SCORE"},{"name":"SUPPLIER_RISK_SCORE"},{"name":"SUSTAINABILITY_SCORE"}]}]}');
