-- L8 Action: recommendations, audit trail, alerts and supporting procedures
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- Release train and environment procedures are in 90_release.sql and 91_release_train.sql.
USE DATABASE ZERO_TO_ONE_CHAIN;

create or replace TABLE ZERO_TO_ONE_CHAIN.L8_ACTION.DECISION_AUDIT (
	AUDIT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	RECOMMENDATION_ID NUMBER(38,0),
	ACTION_TYPE VARCHAR(16777216) NOT NULL,
	ACTION_BY VARCHAR(16777216) NOT NULL,
	ACTION_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	ROLE_USED VARCHAR(16777216),
	PREVIOUS_STATUS VARCHAR(16777216),
	NEW_STATUS VARCHAR(16777216),
	NOTES VARCHAR(16777216),
	EVIDENCE_SNAPSHOT VARIANT
);

create or replace TABLE ZERO_TO_ONE_CHAIN.L8_ACTION.ENVIRONMENT_REGISTRY (
	PROMOTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	PROMOTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SOURCE_ENV VARCHAR(16777216) NOT NULL,
	TARGET_ENV VARCHAR(16777216) NOT NULL,
	PROMOTED_BY VARCHAR(16777216) NOT NULL,
	DBT_TEST_RESULT VARCHAR(16777216),
	CIRCUIT_BREAKER_RESULT VARCHAR(16777216),
	STATUS VARCHAR(16777216) NOT NULL,
	NOTES VARCHAR(16777216)
);

create or replace TABLE ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS (
	RECOMMENDATION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CATEGORY VARCHAR(16777216) NOT NULL,
	SEVERITY VARCHAR(16777216) NOT NULL,
	TITLE VARCHAR(16777216) NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	AFFECTED_ENTITY_TYPE VARCHAR(16777216),
	AFFECTED_ENTITY_ID VARCHAR(16777216),
	RECOMMENDED_ACTION VARCHAR(16777216),
	ESTIMATED_IMPACT_USD NUMBER(15,2),
	ESTIMATED_RISK_REDUCTION_PCT NUMBER(5,2),
	SUPPORTING_EVIDENCE VARIANT,
	STATUS VARCHAR(16777216) DEFAULT 'PENDING',
	ASSIGNED_TO VARCHAR(16777216),
	APPROVED_BY VARCHAR(16777216),
	APPROVED_AT TIMESTAMP_LTZ(9),
	REJECTED_REASON VARCHAR(16777216),
	IMPLEMENTED_AT TIMESTAMP_LTZ(9)
);

create or replace view ZERO_TO_ONE_CHAIN.L8_ACTION.VW_PIPELINE_HEALTH(
	TASK_NAME,
	STATE,
	SCHEDULED_TIME,
	COMPLETED_TIME,
	DURATION_SECONDS,
	ERROR_CODE,
	ERROR_MESSAGE,
	RETURN_VALUE
) as
SELECT
    name AS task_name,
    state,
    scheduled_time,
    completed_time,
    DATEDIFF(SECOND, scheduled_time, completed_time) AS duration_seconds,
    error_code,
    error_message,
    return_value
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD(DAY, -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 100
))
WHERE DATABASE_NAME = 'ZERO_TO_ONE_CHAIN'
ORDER BY scheduled_time DESC;

CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L8_ACTION.SP_PROMOTE_DEV_TO_UAT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    -- Gate: check DQ quarantine in DEV
    LET critical_count NUMBER := (SELECT COUNT(*) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE WHERE severity = ''CRITICAL'' AND resolved_at IS NULL);

    IF (:critical_count > 0) THEN
        INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.ENVIRONMENT_REGISTRY
            (source_env, target_env, promoted_by, circuit_breaker_result, status, notes)
        VALUES (''DEV'', ''UAT'', CURRENT_USER(), ''BLOCKED: '' || :critical_count || '' critical issues'',
                ''BLOCKED'', ''Promotion blocked — resolve critical DQ issues first'');
        RETURN ''BLOCKED: '' || :critical_count || '' critical DQ issues in DEV. Resolve before promoting.'';
    END IF;

    -- Refresh UAT L1 raw data from DEV
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_SALES_ORDERS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_TMS_SHIPMENTS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_SRM_SUPPLIER_PERFORMANCE AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_SRM_SUPPLIER_PERFORMANCE;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_IOT_SENSOR_READINGS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_IOT_SENSOR_READINGS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_VENDORS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_SRM_SUPPLIERS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_SRM_SUPPLIERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_MATERIALS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_MATERIALS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_PLANTS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PLANTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_CUSTOMERS AS SELECT * FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS;

    -- Grant roles
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_ADMIN;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_PLANNER;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_PROCUREMENT;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_LOGISTICS;

    -- Log
    INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.ENVIRONMENT_REGISTRY
        (source_env, target_env, promoted_by, circuit_breaker_result, dbt_test_result, status, notes)
    VALUES (''DEV'', ''UAT'', CURRENT_USER(), ''PASSED: 0 critical'', ''PENDING — run dbt test --target uat'',
            ''SUCCESS'', ''L1 data promoted. Run dbt run + test against UAT to complete.'');

    RETURN ''SUCCESS: DEV data promoted to UAT. Now run dbt --target uat to build transformations.'';
END';

CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L8_ACTION.SP_PROMOTE_UAT_TO_PROD()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    -- Gate 1: check UAT has tables
    LET table_count NUMBER := (SELECT COUNT(*) FROM ZERO_TO_ONE_CHAIN_UAT.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ''L1_INGESTION'');
    IF (:table_count = 0) THEN
        RETURN ''BLOCKED: UAT has no L1 tables. Promote DEV to UAT first.'';
    END IF;

    -- Gate 2: check UAT DQ (quarantine table may not exist in UAT yet, so check DEV)
    LET critical_count NUMBER := (SELECT COUNT(*) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE WHERE severity = ''CRITICAL'' AND resolved_at IS NULL);
    IF (:critical_count > 0) THEN
        INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.ENVIRONMENT_REGISTRY
            (source_env, target_env, promoted_by, circuit_breaker_result, status, notes)
        VALUES (''UAT'', ''PROD'', CURRENT_USER(), ''BLOCKED: '' || :critical_count || '' critical issues'',
                ''BLOCKED'', ''PROD promotion blocked — resolve critical issues'');
        RETURN ''BLOCKED: '' || :critical_count || '' critical issues. Fix before promoting to PROD.'';
    END IF;

    -- Refresh PROD L1 data from UAT
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_SALES_ORDERS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_SALES_ORDERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_TMS_SHIPMENTS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_TMS_SHIPMENTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_SRM_SUPPLIER_PERFORMANCE AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_SRM_SUPPLIER_PERFORMANCE;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_IOT_SENSOR_READINGS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_IOT_SENSOR_READINGS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_VENDORS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_VENDORS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_SRM_SUPPLIERS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_SRM_SUPPLIERS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_MATERIALS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_MATERIALS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_PLANTS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_PLANTS;
    CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN_PROD.L1_INGESTION.RAW_ERP_CUSTOMERS AS SELECT * FROM ZERO_TO_ONE_CHAIN_UAT.L1_INGESTION.RAW_ERP_CUSTOMERS;

    -- Grant roles
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_ADMIN;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_PLANNER;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_PROCUREMENT;
    GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_LOGISTICS;

    -- Log
    INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.ENVIRONMENT_REGISTRY
        (source_env, target_env, promoted_by, circuit_breaker_result, dbt_test_result, status, notes)
    VALUES (''UAT'', ''PROD'', CURRENT_USER(), ''PASSED'', ''PENDING — run dbt test --target prod'',
            ''SUCCESS'', ''UAT data promoted to PROD. Run dbt run + test against PROD to complete.'');

    RETURN ''SUCCESS: UAT promoted to PROD. Now run dbt --target prod to build transformations.'';
END';

create or replace alert ZERO_TO_ONE_CHAIN.L8_ACTION.ALERT_DQ_CRITICAL
	warehouse=Z21_WH
	schedule='USING CRON 0 * * * * UTC'
	if (exists(
		SELECT 1
        FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE
        WHERE severity = 'CRITICAL' AND resolved_at IS NULL
        HAVING COUNT(*) > 50
	))
	then
	INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS
            (category, severity, title, description, recommended_action, status)
        VALUES ('QUALITY', 'CRITICAL',
                'DQ circuit breaker: >50 critical issues in quarantine',
                'Data quality quarantine has accumulated critical issues. Pipeline may be halted.',
                'Review quarantine table, resolve critical issues, then re-run circuit breaker.',
                'PENDING');

create or replace alert ZERO_TO_ONE_CHAIN.L8_ACTION.ALERT_OTD_SLA_BREACH
	warehouse=Z21_WH
	schedule='USING CRON 0 */6 * * * UTC'
	if (exists(
		SELECT 1
        FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_OTD
        WHERE ORDER_DATE >= DATEADD(DAY, -7, CURRENT_DATE())
        HAVING AVG(CASE WHEN IS_ON_TIME THEN 1 ELSE 0 END) * 100 < 85
	))
	then
	INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS
            (category, severity, title, description, recommended_action, status)
        VALUES ('DELIVERY', 'CRITICAL',
                'OTD below 85% SLA in last 7 days',
                'On-Time Delivery has dropped below the 85% SLA threshold. Immediate action required.',
                'Review late orders, identify root causes, expedite pending shipments.',
                'PENDING');

create or replace alert ZERO_TO_ONE_CHAIN.L8_ACTION.ALERT_STOCKOUT
	warehouse=Z21_WH
	schedule='USING CRON 0 */4 * * * UTC'
	if (exists(
		SELECT 1
        FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.VW_METRIC_INVENTORY
        WHERE STOCK_STATUS = 'STOCKOUT'
        HAVING COUNT(*) > 5
	))
	then
	INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS
            (category, severity, title, description, recommended_action, status)
        VALUES ('INVENTORY', 'HIGH',
                'Multiple stockouts detected',
                'More than 5 items are at stockout level. Review and place emergency orders.',
                'Identify critical stockout items, prioritize by ABC class, place emergency POs.',
                'PENDING');
