-- L3 Validate: quarantine, circuit breaker, data metric functions, hourly task DAG
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
USE DATABASE ZERO_TO_ONE_CHAIN;

create or replace TABLE ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (
	QUARANTINE_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	SOURCE_TABLE VARCHAR(16777216),
	SOURCE_KEY VARCHAR(16777216),
	RULE_NAME VARCHAR(16777216),
	RULE_CATEGORY VARCHAR(16777216),
	FAILURE_REASON VARCHAR(16777216),
	ORIGINAL_VALUE VARIANT,
	SEVERITY VARCHAR(16777216),
	QUARANTINED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	RESOLVED_AT TIMESTAMP_LTZ(9),
	RESOLVED_BY VARCHAR(16777216),
	RESOLUTION VARCHAR(16777216)
);

create or replace TABLE ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_REJECTED_PO (
	RN NUMBER(18,0),
	PO_NUMBER VARCHAR(16777216),
	PO_HEADER_ID NUMBER(38,0),
	LINE_NUMBER NUMBER(19,0),
	PO_DATE DATE,
	PO_TYPE VARCHAR(16777216),
	PO_STATUS VARCHAR(16777216),
	VENDOR_CODE VARCHAR(16777216),
	RECEIVING_PLANT VARCHAR(16777216),
	MATERIAL_NUMBER VARCHAR(16777216),
	MATERIAL_GROUP VARCHAR(16777216),
	ORDERED_QTY NUMBER(4,0),
	RECEIVED_QTY NUMBER(4,0),
	REJECTED_QTY NUMBER(2,0),
	UOM VARCHAR(16777216),
	UNIT_PRICE NUMBER(10,2),
	PRICE_CURRENCY VARCHAR(16777216),
	FX_RATE_TO_USD NUMBER(8,4),
	EXTENDED_PRICE_USD NUMBER(25,2),
	DISCOUNT_PCT NUMBER(5,2),
	FREIGHT_COST_USD NUMBER(10,2),
	DUTY_COST_USD NUMBER(10,2),
	HANDLING_COST_USD NUMBER(10,2),
	LANDED_COST_USD NUMBER(28,2),
	REQUESTED_DELIVERY_DATE DATE,
	CONFIRMED_DELIVERY_DATE DATE,
	ACTUAL_DELIVERY_DATE DATE,
	DELIVERY_VARIANCE_DAYS NUMBER(9,0),
	OTD_FLAG VARCHAR(7),
	PRIORITY VARCHAR(16777216),
	ORDER_SOURCE VARCHAR(16777216),
	BUYER_EMAIL VARCHAR(16777216),
	COST_CENTER VARCHAR(16777216),
	PROJECT_CODE VARCHAR(16777216),
	RECEIVING_INSTRUCTION VARCHAR(16777216),
	NOTES VARCHAR(16777216),
	_LOADED_AT TIMESTAMP_LTZ(9),
	_SOURCE_SYSTEM VARCHAR(10),
	REJECTED_AT TIMESTAMP_LTZ(9)
);

create or replace view ZERO_TO_ONE_CHAIN.L3_VALIDATE.VW_DQ_HEALTH_SUMMARY(
	SOURCE_TABLE,
	RULE_CATEGORY,
	SEVERITY,
	ISSUE_COUNT,
	OPEN_ISSUES,
	RESOLVED_ISSUES
) as
SELECT
    source_table,
    rule_category,
    severity,
    COUNT(*) AS issue_count,
    COUNT_IF(resolved_at IS NULL) AS open_issues,
    COUNT_IF(resolved_at IS NOT NULL) AS resolved_issues
FROM DQ_QUARANTINE
GROUP BY source_table, rule_category, severity
ORDER BY
    CASE severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,
    issue_count DESC;

create or replace view ZERO_TO_ONE_CHAIN.L3_VALIDATE.VW_RECONCILE_VENDOR_COUNTS(
	ERP_VENDOR_CODE,
	SRM_SUPPLIER_ID,
	SRM_ERP_REF,
	ERP_PO_COUNT,
	SRM_REPORTED_PO_COUNT,
	COUNT_VARIANCE,
	RECONCILIATION_STATUS
) as
SELECT
    v.vendor_code AS erp_vendor_code,
    s.supplier_id AS srm_supplier_id,
    s.erp_vendor_ref AS srm_erp_ref,
    COUNT(DISTINCT po.po_number) AS erp_po_count,
    s.open_pos_count AS srm_reported_po_count,
    ABS(COUNT(DISTINCT po.po_number) - COALESCE(s.open_pos_count, 0)) AS count_variance,
    CASE WHEN ABS(COUNT(DISTINCT po.po_number) - COALESCE(s.open_pos_count, 0)) > 10 THEN 'MISMATCH'
         ELSE 'OK' END AS reconciliation_status
FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS v
LEFT JOIN ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS po ON po.vendor_code = v.vendor_code
LEFT JOIN ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_SRM_SUPPLIERS s ON s.erp_vendor_ref = v.vendor_code
GROUP BY v.vendor_code, s.supplier_id, s.erp_vendor_ref, s.open_pos_count;

CREATE OR REPLACE DATA METRIC FUNCTION ZERO_TO_ONE_CHAIN.L3_VALIDATE.DMF_NEGATIVE_COUNT("ARG_T" TABLE(NUMBER(38,0)))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS '
    SELECT COUNT_IF(ARG_C < 0) FROM ARG_T
';

CREATE OR REPLACE DATA METRIC FUNCTION ZERO_TO_ONE_CHAIN.L3_VALIDATE.DMF_ORPHAN_VENDOR_COUNT("ARG_T" TABLE(VARCHAR), "ARG_REF" TABLE(VARCHAR))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS '
    SELECT COUNT(*) FROM ARG_T WHERE ARG_C NOT IN (SELECT ARG_REF_C FROM ARG_REF)
';

CREATE OR REPLACE DATA METRIC FUNCTION ZERO_TO_ONE_CHAIN.L3_VALIDATE.DMF_OUT_OF_RANGE_PCT("ARG_T" TABLE(NUMBER(38,0)))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS '
    SELECT ROUND(DIV0(COUNT_IF(ARG_C < 0 OR ARG_C > 100), COUNT(*)) * 100, 2) FROM ARG_T
';

CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L3_VALIDATE.SP_CIRCUIT_BREAKER("THRESHOLD" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    LET critical_count NUMBER := (SELECT COUNT_IF(severity = ''CRITICAL'' AND resolved_at IS NULL) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE);
    LET high_count NUMBER := (SELECT COUNT_IF(severity = ''HIGH'' AND resolved_at IS NULL) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE);
    LET total_open NUMBER := (SELECT COUNT_IF(resolved_at IS NULL) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE);
    IF (:critical_count > 0) THEN
        RETURN ''CIRCUIT_OPEN: '' || :critical_count || '' CRITICAL issues. Pipeline HALTED.'';
    ELSEIF (:high_count > :THRESHOLD) THEN
        RETURN ''CIRCUIT_WARN: '' || :high_count || '' HIGH issues exceed threshold '' || :THRESHOLD;
    ELSE
        RETURN ''CIRCUIT_CLOSED: '' || :total_open || '' open issues within tolerance. Pipeline OK.'';
    END IF;
END';

CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L3_VALIDATE.SP_REFRESH_QUARANTINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    TRUNCATE TABLE ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE;
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (source_table, source_key, rule_name, rule_category, failure_reason, severity)
    SELECT ''RAW_ERP_PURCHASE_ORDERS'', po_number, ''NEGATIVE_QTY'', ''Integrity'', ''ordered_qty = '' || ordered_qty::VARCHAR, ''HIGH''
    FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS WHERE ordered_qty < 0;
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (source_table, source_key, rule_name, rule_category, failure_reason, severity)
    SELECT ''RAW_ERP_PURCHASE_ORDERS'', po_number, ''MISSING_VENDOR'', ''Completeness'', ''vendor_code is NULL'', ''CRITICAL''
    FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS WHERE vendor_code IS NULL;
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (source_table, source_key, rule_name, rule_category, failure_reason, severity)
    SELECT ''RAW_ERP_SALES_ORDERS'', order_number, ''FUTURE_ORDER_DATE'', ''Timeliness'', ''order_date = '' || order_date::VARCHAR, ''MEDIUM''
    FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS WHERE order_date > CURRENT_DATE();
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (source_table, source_key, rule_name, rule_category, failure_reason, severity)
    SELECT ''RAW_TMS_SHIPMENTS'', shipment_id, ''NEGATIVE_WEIGHT'', ''Integrity'', ''gross_weight_kg = '' || gross_weight_kg::VARCHAR, ''HIGH''
    FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS WHERE gross_weight_kg < 0;
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE (source_table, source_key, rule_name, rule_category, failure_reason, severity)
    SELECT ''RAW_TMS_SHIPMENTS'', shipment_id, ''MISSING_CARRIER'', ''Completeness'', ''carrier_code is NULL'', ''CRITICAL''
    FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS WHERE carrier_code IS NULL;
    RETURN ''Quarantine refreshed'';
END';

CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L3_VALIDATE.SP_RESOLVE_QUARANTINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    CREATE TABLE IF NOT EXISTS ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_REJECTED_PO
        AS SELECT *, CURRENT_TIMESTAMP() AS rejected_at FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS WHERE 1=0;
    INSERT INTO ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_REJECTED_PO
        SELECT *, CURRENT_TIMESTAMP() FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
        WHERE vendor_code IS NULL OR ordered_qty < 0;
    LET n NUMBER := SQLROWCOUNT;
    DELETE FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS WHERE vendor_code IS NULL OR ordered_qty < 0;
    DELETE FROM ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS WHERE carrier_code IS NULL OR gross_weight_kg < 0;
    UPDATE ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE
        SET resolved_at = CURRENT_TIMESTAMP(), resolved_by = CURRENT_USER(), resolution = ''Archived to DQ_REJECTED_PO and removed from raw''
        WHERE resolved_at IS NULL;
    INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.DECISION_AUDIT (action_type, action_by, role_used, previous_status, new_status, notes)
        VALUES (''DQ_REMEDIATION'', CURRENT_USER(), CURRENT_ROLE(), ''QUARANTINED'', ''RESOLVED'', :n || '' PO rows archived and removed'');
    RETURN ''RESOLVED: '' || :n || '' defective PO rows archived; quarantine cleared.'';
END';

create or replace task ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_ANOMALY_SCAN
	warehouse=Z21_WH
	after ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_CIRCUIT_BREAKER
	as SELECT COUNT(*) FROM ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.VW_INVENTORY_ANOMALIES;

create or replace task ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_CIRCUIT_BREAKER
	warehouse=Z21_WH
	after ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_DQ_REFRESH
	as CALL ZERO_TO_ONE_CHAIN.L3_VALIDATE.SP_CIRCUIT_BREAKER(200);

create or replace task ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_CONSISTENCY_REFRESH
	warehouse=Z21_WH
	after ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_CIRCUIT_BREAKER
	as CALL ZERO_TO_ONE_CHAIN.L6_SEMANTIC.SP_REFRESH_CONSISTENCY();

create or replace task ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_DQ_REFRESH
	warehouse=Z21_WH
	schedule='USING CRON 0 * * * * UTC'
	COMMENT='Root task: refresh DQ quarantine from raw tables'
	as CALL ZERO_TO_ONE_CHAIN.L3_VALIDATE.SP_REFRESH_QUARANTINE();

create or replace task ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_PIPELINE_LOG
	warehouse=Z21_WH
	after ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_ANOMALY_SCAN, ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_CONSISTENCY_REFRESH
	as INSERT INTO ZERO_TO_ONE_CHAIN.L8_ACTION.DECISION_AUDIT
        (recommendation_id, action_type, action_by, role_used, previous_status, new_status, notes)
    VALUES (NULL, 'PIPELINE_COMPLETE', 'SYSTEM', 'Z21_ADMIN', 'RUNNING', 'COMPLETED',
            'Pipeline DAG completed at ' || CURRENT_TIMESTAMP()::VARCHAR);
