-- Governance: where the policies, tags and data metric functions are applied
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- Run after governance/01_policies_and_tags.sql and L3_validate/01_validation.sql.
USE DATABASE ZERO_TO_ONE_CHAIN;

-- RAW_ERP_CUSTOMERS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS ADD ROW ACCESS POLICY ZERO_TO_ONE_CHAIN.GOVERNANCE.RAP_REGION_ACCESS ON (CUSTOMER_REGION);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS MODIFY COLUMN PRIMARY_CONTACT_EMAIL SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'PII';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS MODIFY COLUMN PRIMARY_CONTACT_PHONE SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'PII';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'CUSTOMER';

-- RAW_ERP_INVENTORY_SNAPSHOTS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'INVENTORY';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_INVENTORY_SNAPSHOTS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_FRESHNESS = 'DAILY';

-- RAW_ERP_PURCHASE_ORDERS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS MODIFY COLUMN UNIT_PRICE SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'FINANCIAL';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS MODIFY COLUMN BUYER_EMAIL SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'PII';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'PROCUREMENT';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_FRESHNESS = 'HOURLY';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (PO_NUMBER);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (VENDOR_CODE);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (MATERIAL_NUMBER);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS ADD DATA METRIC FUNCTION ZERO_TO_ONE_CHAIN.L3_VALIDATE.DMF_NEGATIVE_COUNT ON (ORDERED_QTY);

-- RAW_ERP_SALES_ORDERS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'CUSTOMER';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_NUMBER);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_SALES_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- RAW_ERP_VENDORS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS MODIFY COLUMN CONTACT_EMAIL SET MASKING POLICY ZERO_TO_ONE_CHAIN.GOVERNANCE.MASK_CONTACT_EMAIL;
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS MODIFY COLUMN ANNUAL_SPEND_USD_MM SET MASKING POLICY ZERO_TO_ONE_CHAIN.GOVERNANCE.MASK_SUPPLIER_COST;
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS MODIFY COLUMN ANNUAL_SPEND_USD_MM SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'FINANCIAL';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS MODIFY COLUMN CONTACT_PHONE SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'PII';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS MODIFY COLUMN CONTACT_EMAIL SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_SENSITIVITY = 'PII';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'SUPPLIER';

-- RAW_IOT_SENSOR_READINGS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_IOT_SENSOR_READINGS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'QUALITY';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_IOT_SENSOR_READINGS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_FRESHNESS = 'REAL_TIME';

-- RAW_SRM_SUPPLIERS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_SRM_SUPPLIERS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'SUPPLIER';

-- RAW_TMS_SHIPMENTS
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS SET TAG ZERO_TO_ONE_CHAIN.GOVERNANCE.DATA_DOMAIN = 'LOGISTICS';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (SHIPMENT_ID);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_TMS_SHIPMENTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
