-- L7 Intelligence: Snowflake ML: OTD forecast and inventory anomaly detection
-- Reference DDL extracted from the deployed DEV database ZERO_TO_ONE_CHAIN (GET_DDL), so it matches what is running.
-- Other environments are built from DEV by SP_DEPLOY_ENVIRONMENT (see 90_release.sql).
-- Models are trained inside the warehouse on the views below; scheduled scoring writes OTD_FORECAST_RESULTS.
USE DATABASE ZERO_TO_ONE_CHAIN;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.Z21_OTD_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.VW_OTD_SIMPLE_SERIES'),
  TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'OTD_PCT');

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.Z21_INVENTORY_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.VW_INVENTORY_ANOMALY_INPUT'),
  TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'INVENTORY_VALUE', SERIES_COLNAME => 'SERIES', LABEL_COLNAME => '');
