-- ============================================================
-- 01_setup.sql — Foundation: database, schemas, roles, warehouse
-- Zero to One Chain · Supply Chain Decision Twin
-- Idempotent — safe to re-run
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- DATABASE
-- ============================================================
CREATE DATABASE IF NOT EXISTS ZERO_TO_ONE_CHAIN
    COMMENT = 'Supply Chain Decision Twin — CoCo CLI Hackathon GCC Edition';

USE DATABASE ZERO_TO_ONE_CHAIN;

-- ============================================================
-- SCHEMAS (one per architectural layer + support schemas)
-- ============================================================
CREATE SCHEMA IF NOT EXISTS L1_INGESTION    COMMENT = 'Raw data from ERP, TMS, SRM, IoT, documents';
CREATE SCHEMA IF NOT EXISTS L2_STAGE        COMMENT = 'Typed, normalized, deduped, CDC';
CREATE SCHEMA IF NOT EXISTS L3_VALIDATE     COMMENT = 'DQ rules, quarantine, reconciliation';
CREATE SCHEMA IF NOT EXISTS L4_HARMONIZE    COMMENT = 'Entity resolution, golden records, crosswalk';
CREATE SCHEMA IF NOT EXISTS L5_CORE         COMMENT = 'Conformed entities, ontology graph, SCD2 history';
CREATE SCHEMA IF NOT EXISTS L6_SEMANTIC     COMMENT = 'Semantic views, canonical metrics';
CREATE SCHEMA IF NOT EXISTS L7_INTELLIGENCE COMMENT = 'Cortex Agent, Search service, ML models';
CREATE SCHEMA IF NOT EXISTS L8_ACTION       COMMENT = 'Recommendations, approvals, audit trail';
CREATE SCHEMA IF NOT EXISTS L9_EXPERIENCE   COMMENT = 'Streamlit app objects';
CREATE SCHEMA IF NOT EXISTS GOVERNANCE      COMMENT = 'Policies, tags, lineage proofs';
CREATE SCHEMA IF NOT EXISTS DATA_GEN        COMMENT = 'Synthetic data generation procedures';

-- ============================================================
-- WAREHOUSE
-- ============================================================
CREATE WAREHOUSE IF NOT EXISTS Z21_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Zero to One Chain compute';

USE WAREHOUSE Z21_WH;

-- ============================================================
-- RESOURCE MONITOR (cost guardrail)
-- ============================================================
CREATE OR REPLACE RESOURCE MONITOR Z21_MONITOR
    WITH CREDIT_QUOTA = 20
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE Z21_WH SET RESOURCE_MONITOR = Z21_MONITOR;

-- ============================================================
-- ROLES (persona-based)
-- ============================================================
CREATE ROLE IF NOT EXISTS Z21_ADMIN;
CREATE ROLE IF NOT EXISTS Z21_PLANNER;
CREATE ROLE IF NOT EXISTS Z21_PROCUREMENT;
CREATE ROLE IF NOT EXISTS Z21_LOGISTICS;

-- Hierarchy: ACCOUNTADMIN → Z21_ADMIN → persona roles
GRANT ROLE Z21_ADMIN       TO ROLE ACCOUNTADMIN;
GRANT ROLE Z21_PLANNER     TO ROLE Z21_ADMIN;
GRANT ROLE Z21_PROCUREMENT TO ROLE Z21_ADMIN;
GRANT ROLE Z21_LOGISTICS   TO ROLE Z21_ADMIN;

-- Database-level grants
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_ADMIN;
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_PLANNER;
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_LOGISTICS;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE Z21_WH TO ROLE Z21_ADMIN;
GRANT USAGE ON WAREHOUSE Z21_WH TO ROLE Z21_PLANNER;
GRANT USAGE ON WAREHOUSE Z21_WH TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON WAREHOUSE Z21_WH TO ROLE Z21_LOGISTICS;

-- Schema grants: admin gets all, persona roles get L5+ (curated and above)
GRANT ALL ON ALL SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_ADMIN;
GRANT USAGE ON SCHEMA L5_CORE         TO ROLE Z21_PLANNER;
GRANT USAGE ON SCHEMA L5_CORE         TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON SCHEMA L5_CORE         TO ROLE Z21_LOGISTICS;
GRANT USAGE ON SCHEMA L6_SEMANTIC     TO ROLE Z21_PLANNER;
GRANT USAGE ON SCHEMA L6_SEMANTIC     TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON SCHEMA L6_SEMANTIC     TO ROLE Z21_LOGISTICS;
GRANT USAGE ON SCHEMA L7_INTELLIGENCE TO ROLE Z21_PLANNER;
GRANT USAGE ON SCHEMA L7_INTELLIGENCE TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON SCHEMA L7_INTELLIGENCE TO ROLE Z21_LOGISTICS;
GRANT USAGE ON SCHEMA L8_ACTION       TO ROLE Z21_PLANNER;
GRANT USAGE ON SCHEMA L8_ACTION       TO ROLE Z21_PROCUREMENT;
GRANT USAGE ON SCHEMA L8_ACTION       TO ROLE Z21_LOGISTICS;

-- Future grants for tables/views in curated+ schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA L5_CORE     TO ROLE Z21_PLANNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA L5_CORE     TO ROLE Z21_PROCUREMENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA L5_CORE     TO ROLE Z21_LOGISTICS;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA L5_CORE     TO ROLE Z21_PLANNER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA L5_CORE     TO ROLE Z21_PROCUREMENT;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA L5_CORE     TO ROLE Z21_LOGISTICS;

GRANT SELECT ON FUTURE TABLES IN SCHEMA L6_SEMANTIC  TO ROLE Z21_PLANNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA L6_SEMANTIC  TO ROLE Z21_PROCUREMENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA L6_SEMANTIC  TO ROLE Z21_LOGISTICS;

-- Tag the database
ALTER DATABASE ZERO_TO_ONE_CHAIN SET TAG SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'SENSITIVE';

SELECT '✅ Setup complete — database, schemas, roles, warehouse, resource monitor' AS status;
