-- Roles and grants for the shared read-only viewer app (one statement per line)
CREATE ROLE IF NOT EXISTS Z21_APP_OWNER COMMENT = 'Owner role of the shared viewer app: read-only on the project'
CREATE ROLE IF NOT EXISTS Z21_APP_VIEWER COMMENT = 'Grant to people who may open the shared viewer app'
GRANT USAGE ON WAREHOUSE Z21_WH TO ROLE Z21_APP_OWNER
GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE Z21_APP_OWNER
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL TABLES IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL VIEWS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL SEMANTIC VIEWS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT MONITOR ON ALL TASKS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL TABLES IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL SEMANTIC VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT MONITOR ON ALL TASKS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT USAGE ON DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT USAGE ON ALL SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL TABLES IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON ALL SEMANTIC VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT MONITOR ON ALL TASKS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT MONITOR ON FUTURE TASKS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE TABLES IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE VIEWS IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN TO ROLE Z21_APP_OWNER
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT MONITOR ON FUTURE TASKS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE TABLES IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN_UAT TO ROLE Z21_APP_OWNER
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT MONITOR ON FUTURE TASKS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE TABLES IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE VIEWS IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE ZERO_TO_ONE_CHAIN_PROD TO ROLE Z21_APP_OWNER
GRANT CREATE STREAMLIT ON SCHEMA ZERO_TO_ONE_CHAIN.L9_EXPERIENCE TO ROLE Z21_APP_OWNER
GRANT ROLE Z21_APP_VIEWER TO ROLE ACCOUNTADMIN
GRANT ROLE Z21_APP_OWNER TO USER SID
-- Deploy: PUT the app files plus a viewer.flag file to @ZERO_TO_ONE_CHAIN.L9_EXPERIENCE.APP_SOURCE, then
-- CREATE OR REPLACE STREAMLIT ZERO_TO_ONE_CHAIN.L9_EXPERIENCE.ZERO_TO_ONE_CHAIN_APP FROM '@ZERO_TO_ONE_CHAIN.L9_EXPERIENCE.APP_SOURCE' MAIN_FILE='streamlit_app.py' QUERY_WAREHOUSE=Z21_WH RUNTIME_NAME='SYSTEM$ST_CONTAINER_RUNTIME_PY3_11' COMPUTE_POOL=SYSTEM_COMPUTE_POOL_CPU;
-- GRANT USAGE ON STREAMLIT ZERO_TO_ONE_CHAIN.L9_EXPERIENCE.ZERO_TO_ONE_CHAIN_APP TO ROLE Z21_APP_VIEWER;
