-- Ask the Twin: tools and grants for the in-app assistant (run statements one at a time)

-- 1. live project state tool (read-only)
CREATE OR REPLACE PROCEDURE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SP_PROJECT_STATUS(SECTION VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Read-only snapshot of live project state (pipeline, release train, approvals, data quality, consistency). Tool project_status of SUPPLY_CHAIN_TWIN.'
EXECUTE AS OWNER
AS
$$
DECLARE
  v VARCHAR;
BEGIN
  v := (SELECT TO_VARCHAR(OBJECT_CONSTRUCT(
    'pipeline_tasks_started_of_total', OBJECT_CONSTRUCT(
      'DEV',  (SELECT COUNT_IF(state = 'started') || ' of ' || COUNT(*) FROM TABLE(ZERO_TO_ONE_CHAIN.INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => 'ZERO_TO_ONE_CHAIN.L3_VALIDATE.TASK_DQ_REFRESH', RECURSIVE => TRUE))),
      'UAT',  (SELECT COUNT_IF(state = 'started') || ' of ' || COUNT(*) FROM TABLE(ZERO_TO_ONE_CHAIN_UAT.INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => 'ZERO_TO_ONE_CHAIN_UAT.L3_VALIDATE.TASK_DQ_REFRESH', RECURSIVE => TRUE))),
      'PROD', (SELECT COUNT_IF(state = 'started') || ' of ' || COUNT(*) FROM TABLE(ZERO_TO_ONE_CHAIN_PROD.INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => 'ZERO_TO_ONE_CHAIN_PROD.L3_VALIDATE.TASK_DQ_REFRESH', RECURSIVE => TRUE)))),
    'recent_release_train_runs', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('train_id', train_id, 'checked_at', checked_at::VARCHAR, 'status', status, 'trigger', trigger_type, 'decided_by', decided_by, 'prod_released_at', prod_released_at::VARCHAR)) WITHIN GROUP (ORDER BY train_id DESC)
                                  FROM (SELECT * FROM ZERO_TO_ONE_CHAIN.L8_ACTION.RELEASE_TRAIN ORDER BY train_id DESC LIMIT 6)),
    'recommendations_by_status', (SELECT OBJECT_AGG(status, n) FROM (SELECT status, COUNT(*) n FROM ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS GROUP BY status)),
    'pending_recommendations', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('id', recommendation_id, 'category', category, 'severity', severity, 'title', title, 'estimated_impact_usd', estimated_impact_usd)) WITHIN GROUP (ORDER BY estimated_impact_usd DESC NULLS LAST)
                                FROM (SELECT * FROM ZERO_TO_ONE_CHAIN.L8_ACTION.RECOMMENDATIONS WHERE status = 'PENDING' ORDER BY estimated_impact_usd DESC NULLS LAST LIMIT 10)),
    'recent_decisions', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('at', action_at::VARCHAR, 'by', action_by, 'role', role_used, 'action', action_type, 'from', previous_status, 'to', new_status, 'note', notes)) WITHIN GROUP (ORDER BY action_at DESC)
                         FROM (SELECT * FROM ZERO_TO_ONE_CHAIN.L8_ACTION.DECISION_AUDIT ORDER BY action_at DESC LIMIT 5)),
    'data_quality_open_issues_by_severity', (SELECT COALESCE(OBJECT_AGG(severity, n), OBJECT_CONSTRUCT()) FROM (SELECT severity, SUM(open_issues) n FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.VW_DQ_HEALTH_SUMMARY GROUP BY severity)),
    'data_quality_open_quarantined_records', (SELECT COUNT(*) FROM ZERO_TO_ONE_CHAIN.L3_VALIDATE.DQ_QUARANTINE WHERE resolved_at IS NULL),
    'consistency_proof_latest', (SELECT OBJECT_CONSTRUCT('run_at', MAX(run_at)::VARCHAR, 'metrics_checked', COUNT(*), 'metrics_identical_across_personas', COUNT_IF(all_match))
                                 FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.CONSISTENCY_PROOF WHERE run_at = (SELECT MAX(run_at) FROM ZERO_TO_ONE_CHAIN.L6_SEMANTIC.CONSISTENCY_PROOF)),
    'business_date', '2026-10-05'
  )));
  RETURN v;
END;
$$;

-- 2. project knowledge base (searched by the agent tool project_guide)
CREATE OR REPLACE TABLE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.PROJECT_KNOWLEDGE (DOC_ID NUMBER AUTOINCREMENT, TOPIC VARCHAR, TITLE VARCHAR, CONTENT VARCHAR);
INSERT INTO ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.PROJECT_KNOWLEDGE (TOPIC, TITLE, CONTENT)
SELECT * FROM VALUES
('Overview','What is Zero to One Chain',$$Zero to One Chain is a Supply Chain Decision Twin built entirely inside Snowflake. It solves the problem of conflicting numbers: Planning, Procurement and Logistics each used to compute on-time delivery their own way, so the same question had three answers. The twin connects ERP, TMS and SRM data into one ontology (suppliers, parts, plants, customers, orders, shipments), defines every metric once in a governed semantic view, lets people ask questions in plain English through a Cortex Agent, and carries every recommended action from the raw row that triggered it to a human approval with a full audit trail. Team: Zero to One Chain, leader Siddharth Shastri, team size 1. Hackathon problem statement: Supply Chain Ontology and Governed Conversational Analytics (Snowflake CoCo CLI Hackathon, GCC Edition).$$),
('Architecture','Nine-layer architecture',$$The platform has 9 layers. L1 Ingestion: 11 raw source tables, about 544K rows (ERP sales orders, purchase orders, inventory snapshots, materials, plants, customers, vendors; TMS shipments; SRM suppliers and supplier performance; IoT sensor readings). L2 Stage: dbt staging views and Dynamic Tables that type and clean the data. L3 Validate: data-quality quarantine, circuit breaker, data metric functions. L4 Harmonize: Dynamic Tables doing entity resolution between ERP vendors and SRM suppliers (golden suppliers, crosswalks). L5 Core: dbt marts with facts and dimensions plus the ontology edges table; 41 dbt tests. L6 Semantic: the SUPPLY_CHAIN_ANALYTICS semantic view with canonical metrics and a consistency proof. L7 Intelligence: Cortex Agent, Cortex Analyst, Cortex Search, ML forecast and anomaly detection, what-if views. L8 Action: recommendations, approvals, alerts, audit trail, release train. L9 Experience: this Streamlit decision app. Each layer reads only the one before it, so a layer can be swapped without touching the others.$$),
('Architecture','Data sources and volumes',$$Structured sources: ERP (about 100K sales orders, 100K purchase orders, inventory snapshots, materials, plants, customers, vendors), TMS (about 80K shipments), SRM (suppliers and supplier performance) and IoT sensor readings: 11 raw tables and about 544K rows in total. Unstructured sources: 200 documents (supplier contracts, SLAs, SOPs and policies, incident reports, audit results, risk assessments) indexed by the Cortex Search service SC_DOCUMENT_SEARCH. The data is realistic synthetic data generated for the demo; the next step is to replace it with live feeds using Snowpipe Streaming or Openflow.$$),
('Ontology','Ontology and entity resolution',$$The ontology links suppliers to the parts they supply, parts to plants and open customer orders, and orders to customers and shipments. It is stored as edges in L5_CORE.ONTOLOGY_EDGES. Entity resolution in L4 reconciles ERP vendor codes with SRM supplier records into golden supplier records through crosswalk tables (XWALK_VENDOR_SUPPLIER, XWALK_REGIONS). Walking this graph is what powers the disruption simulator: supplier to parts it sources to open orders needing those parts to customers who feel the outage, including which customers have a contractual SLA.$$),
('Semantic layer','Canonical metric definitions and targets',$$Every metric has exactly one definition, held in the semantic view ZERO_TO_ONE_CHAIN.L6_SEMANTIC.SUPPLY_CHAIN_ANALYTICS. On-Time Delivery (OTD) is the share of DELIVERED order lines delivered on or before the committed date; target 95%. OTIF is the share of delivered lines that were on time AND in full; target 90%. Fill rate is delivered quantity divided by ordered quantity averaged over delivered lines; target 98%. Days of inventory, landed cost per unit (price plus freight, duty and handling) and supplier risk score (blended financial, geopolitical and quality signals) are also defined once. Lines not yet delivered are excluded from OTD, OTIF and fill rate. The semantic view contains 4 logical tables (OTD, inventory, landed cost, supplier risk) and 24 verified queries. The app, Cortex Analyst and the agent all read it, which is why they always agree.$$),
('Semantic layer','Consistency proof',$$A scheduled task (TASK_CONSISTENCY_REFRESH) recomputes each canonical metric as the Planning, Procurement and Logistics personas would and records the result in L6_SEMANTIC.CONSISTENCY_PROOF. The latest run shows 6 of 6 metrics identical across all three personas. This is the evidence for the claim one governed truth: if a definition ever diverged, ALL_MATCH would turn false and show up on the Trust and quality page.$$),
('Intelligence','Agent, Analyst and Search',$$The Cortex Agent SUPPLY_CHAIN_TWIN (this assistant) orchestrates tools. Cortex Analyst turns questions into SQL against the governed semantic view, always showing the SQL so it can be verified. Cortex Search (SC_DOCUMENT_SEARCH) answers questions about contracts, SLAs, policies, incidents and audits over 200 documents and cites titles. A project guide tool (this knowledge base) explains how the system works, and a live status tool reads pipeline, release, approval and data-quality state. A separate Remediation agent proposes fixes for quarantined bad records; a human applies them.$$),
('Intelligence','Machine learning',$$Snowflake ML runs inside the warehouse: an OTD forecast (results in L7_INTELLIGENCE.OTD_FORECAST_RESULTS, built on the monthly OTD series) and inventory anomaly detection (views VW_INVENTORY_ANOMALIES and VW_INVENTORY_ANOMALY_INPUT, refreshed by TASK_ANOMALY_SCAN). Anomalies and breached thresholds feed the recommendations queue.$$),
('Governance','Masking, row access, tags and metric functions',$$Governance is enforced in Snowflake at the data, not in the app, so it applies to every tool. Masking policies: supplier spend is visible to Procurement only, and contact emails are masked for non-admin roles. Row access policy: the Logistics role sees only AMERICAS and EMEA customer rows. Classification tags (PII, FINANCIAL) mark sensitive columns. Data metric functions check negative quantities and values, out-of-range rates and orphan suppliers. The three personas (Planning, Procurement, Logistics) therefore see the same definitions but only the data their role allows.$$),
('Data quality','Quarantine, circuit breaker and remediation',$$Bad rows are not silently passed on. L3 rules write failing records to DQ_QUARANTINE (with rule, category, severity, reason and original value) and rejected purchase orders to DQ_REJECTED_PO. The circuit breaker task (SP_CIRCUIT_BREAKER) stops downstream promotion when a critical issue exists: any critical data-quality issue blocks every release to UAT and PROD. The Remediation agent proposes fixes and a human resolves them (SP_RESOLVE_QUARANTINE). Reconciliation views compare ERP and SRM vendor and PO counts. The Trust and quality page shows all of this.$$),
('Engineering','dbt, Dynamic Tables and tasks',$$dbt Projects on Snowflake builds the staging models and the L5 marts (dim_supplier, fact_orders, fact_purchase_orders, mart_customer_delivery, mart_supplier_scorecard) with 41 passing tests, and the same project builds every environment. 14 Dynamic Tables keep harmonized and core layers fresh declaratively. An hourly task DAG runs: TASK_DQ_REFRESH (root, hourly) then TASK_CIRCUIT_BREAKER, then TASK_ANOMALY_SCAN and TASK_CONSISTENCY_REFRESH, then TASK_PIPELINE_LOG, then TASK_RELEASE_TRAIN (DEV only, 6 tasks; UAT and PROD run 5). Three alerts raise recommendations: SLA breach, stockout and critical data-quality issue.$$),
('Environments','DEV, UAT and PROD',$$Three fully separate databases, not clones: ZERO_TO_ONE_CHAIN (DEV, also the control plane), ZERO_TO_ONE_CHAIN_UAT and ZERO_TO_ONE_CHAIN_PROD. Each is built by the same dbt project and contains every layer including the semantic view, search service and agents. The ENVIRONMENT_REGISTRY table records promotions and the Operations page shows the three environments side by side.$$),
('Release train','How a change reaches PROD',$$The release train promotes DEV to UAT automatically and PROD only with human approval. At the end of each hourly DEV run, a content fingerprint (HASH_AGG of every raw table plus a hash of every view, procedure, Dynamic Table, task, semantic view, search service, agent and the dbt project) is compared with the last released snapshot. If nothing changed the run is logged as SKIPPED_NO_CHANGE and costs no extra credits. If something changed: (1) the data-quality gate must pass, (2) data is promoted and dbt builds and tests run in UAT, with a full-stack deploy, (3) UAT is verified: metric parity with DEV, 0 critical DQ issues, and the consistency proof. A verified build raises an approval card in the Action queue (category RELEASE). Approving runs UAT to PROD, but approval is refused if DEV changed after verification, so PROD only ever receives exactly what passed UAT. Newer builds supersede older approval cards. Statuses: SKIPPED_NO_CHANGE, BLOCKED, UAT_FAILED, AWAITING_APPROVAL, PROD_RELEASED, REJECTED, SUPERSEDED.$$),
('Action','Recommendations, approvals and audit',$$Recommendations (L8_ACTION.RECOMMENDATIONS) come from alerts, anomalies, quarantine and the release train, each with severity, estimated impact in USD, supporting evidence and status (PENDING, APPROVED, REJECTED, IMPLEMENTED, SUPERSEDED). A human approves or rejects in the Action queue; the decision, the person, their role, the previous and new status, a note and an evidence snapshot are written to DECISION_AUDIT. Every decision and release is audited with name, role and note.$$),
('Operations','Start/stop and cost control',$$One switch (SP_PROJECT_CONTROL, the Project button in the sidebar of the admin edition) starts or stops the whole project: it suspends or resumes every task and alert in DEV, UAT and PROD, and everything is audited. Data, dashboards and agents stay intact when stopped. Cost controls: resource monitor Z21_MONITOR (20 credits per day), the project warehouse Z21_WH auto-suspends after 60 seconds, and the release train is change-driven so unchanged builds cost nothing.$$),
('App guide','Pages of the decision app',$$Command center: last full quarter (Jul-Sep 2026) compared with Q2, delivered order lines only, with headline OTD, OTIF, fill rate and the key finding. Delivery: root cause of the Q3 on-time decline, focused on APAC customer orders (Jan-Sep 2026). Inventory: snapshot at the business date, days of inventory = on-hand / average daily demand, safety stock = 7 days, stock-outs and anomalies. Suppliers: inbound on-time delivery on received purchase-order lines placed since July 2026, plus risk. Disruption simulator: pick a supplier and an outage length to see which customers are hit and the revenue at risk (walks supplier to parts to open orders to customers). Action queue: recommendations generated from the governed metrics and release approvals; nothing executes without human approval. Trust and quality: why the numbers on every page can be believed (consistency proof, data quality, quarantine). Operations: pipeline control and the governed release train, DEV to UAT automatically, PROD on approval, with the DEV/UAT/PROD cards and train history. Ask the Twin: this assistant. The viewer edition is read-only: Start/Stop project, approvals and remediation are hidden and refused for viewers; the admin edition (owner) has them. There is also a persona switch (Planning, Procurement, Logistics) in the sidebar; every persona reads the same governed metric definitions.$$),
('Demo storyline','Headline findings in the data',$$Business date of the demo data is 2026-10-05. Overall OTD is about 93.1% (target 95%), OTIF about 90.2% (target 90%) across 98,163 delivered lines from Oct 2024 to Oct 2026. APAC ocean-freight on-time delivery fell from 90.5% to 55.8% in Q3 2026. All 8 APAC Platinum and Gold customers are below 90% OTD, with about $15.9M delivered late. In the simulator, a 4-week outage at one supplier hits 9 customers and about $677K of revenue. Use the Analyst tool for exact current numbers rather than relying on this text.$$),
('Technology','Snowflake features and why',$$dbt Projects on Snowflake (versioned, tested transformations); Dynamic Tables (declarative freshness); Tasks and Alerts (hourly DAG with circuit breaker); Semantic View (one home for metric definitions); Cortex Analyst and Cortex Agents (governed natural-language answers with inspectable SQL); Cortex Search (grounding in contracts and SOPs); Snowflake ML (OTD forecast, anomaly detection); Horizon governance (masking, row access, tags, DMFs); Streamlit in Snowflake (decision app next to the data); resource monitor (hard daily credit cap). Built end to end with Snowflake Cortex Code (CoCo) CLI skills.$$),
('Impact','Outcomes and roadmap',$$Measured outcomes: 6 of 6 canonical metrics identical across personas, 0 manual steps from a DEV change to a verified UAT build, 41 of 41 dbt tests passing in every environment, 100% of decisions and releases audited. Scalability: one dbt project builds three environments, refresh is incremental, the semantic layer is reused by any new consumer, and governance is inherited by every tool. Next steps: live ERP/TMS feeds with Snowpipe Streaming or Openflow, more domain models (finance, healthcare supply) on the same ontology, the agent in Snowflake Intelligence and Microsoft Teams, and write-back of approved actions to ERP purchase orders through external access.$$)
AS t(topic, title, content);

CREATE OR REPLACE CORTEX SEARCH SERVICE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SC_PROJECT_KNOWLEDGE
  ON CONTENT ATTRIBUTES TOPIC, TITLE WAREHOUSE = Z21_WH TARGET_LAG = '1 day'
AS (SELECT doc_id::VARCHAR AS doc_id, topic, title, content FROM ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.PROJECT_KNOWLEDGE);

-- 3. agent: create it from cortex_project/SUPPLY_CHAIN_TWIN.agent.yaml with CREATE OR REPLACE AGENT ... FROM SPECIFICATION
--    (recreating drops grants, so run step 4 afterwards)

-- 4. least-privilege access for the viewer app owner role (read-only: the agent cannot change anything)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE Z21_APP_OWNER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE Z21_APP_OWNER;
GRANT USAGE ON AGENT ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SUPPLY_CHAIN_TWIN TO ROLE Z21_APP_OWNER;
GRANT USAGE ON CORTEX SEARCH SERVICE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SC_DOCUMENT_SEARCH TO ROLE Z21_APP_OWNER;
GRANT USAGE ON CORTEX SEARCH SERVICE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SC_PROJECT_KNOWLEDGE TO ROLE Z21_APP_OWNER;
GRANT USAGE ON PROCEDURE ZERO_TO_ONE_CHAIN.L7_INTELLIGENCE.SP_PROJECT_STATUS(VARCHAR) TO ROLE Z21_APP_OWNER;
