-- ============================================================
-- 99_teardown.sql — Clean removal of all project objects
-- Zero to One Chain · Supply Chain Decision Twin
-- ⚠️ DESTRUCTIVE — drops everything
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Remove policies first (must be detached before drop)
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS
    MODIFY COLUMN ANNUAL_SPEND_USD_MM UNSET MASKING POLICY;
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_VENDORS
    MODIFY COLUMN CONTACT_EMAIL UNSET MASKING POLICY;
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_CUSTOMERS
    DROP ROW ACCESS POLICY ZERO_TO_ONE_CHAIN.GOVERNANCE.RAP_REGION_ACCESS;

-- Drop DMFs from tables
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
    DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (vendor_code);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
    DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (material_number);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
    DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (po_number);
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
    DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE ZERO_TO_ONE_CHAIN.L1_INGESTION.RAW_ERP_PURCHASE_ORDERS
    DROP DATA METRIC FUNCTION ZERO_TO_ONE_CHAIN.L3_VALIDATE.DMF_NEGATIVE_COUNT ON (ordered_qty);

-- Drop database (cascades all schemas, tables, views, DTs, agents)
DROP DATABASE IF EXISTS ZERO_TO_ONE_CHAIN;

-- Drop roles
DROP ROLE IF EXISTS Z21_LOGISTICS;
DROP ROLE IF EXISTS Z21_PROCUREMENT;
DROP ROLE IF EXISTS Z21_PLANNER;
DROP ROLE IF EXISTS Z21_ADMIN;

-- Drop warehouse and monitor
DROP WAREHOUSE IF EXISTS Z21_WH;
DROP RESOURCE MONITOR IF EXISTS Z21_MONITOR;

SELECT '✅ Teardown complete — all Zero to One Chain objects removed' AS status;
